### ISSUE TITLE
server.log - AsyncTask

### ISSUE THREAD

**Issue by robske110** [Hydreon/Steadfast2#101]
README says: Saving the server.log is disabled because it takes a lot of time to write to disk
->Why? Saving to disk is run in a async task, so how in the world should it block the main thread

**Comment by tntloverlol** [comment]
We have benchmarked this and it makes a significant difference.

**Comment by robske110** [comment]
1ms per 10 log entrys? Cool sou measure time the processir passes stuff over threads. So high time intensive. Ugh, srsly!

**Comment by thebigsmileXD** [comment]
Doesnt make a big difference on debug level 0..
