### ISSUE TITLE
on join

### ISSUE THREAD

**Issue by Driesboy** [Hydreon/Steadfast2#105]
[Server thread/CRITICAL]: TypeError: "Argument 5 passed to pocketmine\level\format\generic\BaseChunk::__construct() must be of the type array, string given, called in /Users/Ronny/Desktop/V24/src/pocketmine/level/format/anvil/Chunk.php on line 92" (EXCEPTION) in "/src/pocketmine/level/format/generic/BaseChunk" at line 49

**Comment by tntloverlol** [comment]
Anvil worlds are not supported use a mcregion one instead.

**Comment by Driesboy** [comment]
but please support it i dont know how to transfer it

**Comment by Driesboy** [comment]
can you transfer it for me?

**Comment by thebigsmileXD** [comment]
ClearSky does uport Anvil maps party, maybe clone the format to Steadfast. else: https://www.youtube.com/watch?v=rjGfAzdk8Sw

**Comment by Driesboy** [comment]
i am using apple!

**Comment by Muqsit** [comment]
The user crashes when they are in a chunk that was converted from anvil to mcregion.

**Comment by Driesboy** [comment]
i know but how i fix that i am using apple and it dont work for me

**Comment by thebigsmileXD** [comment]
Well, it should work almost the same on apple, open the terminal and execute the thing. Its running with Java

**Comment by Driesboy** [comment]
Yes but it say that the folder world not there
