### ISSUE TITLE
Permission Denied 

### ISSUE THREAD

**Issue by KairusDarkSeeker** [Hydreon/Steadfast2#130]
When I try to use ./installer.sh on a Linux Server, it tells me ` Permission denied `

**Comment by blancsys** [comment]
See my reply on https://github.com/Hydreon/Steadfast2/issues/129

**Comment by KairusDarkSeeker** [comment]
@blancsys okay thx

**Comment by dishrex** [comment]
Please stop opening issues about file system permissions. Read up on how Linux file permissions work: https://www.linux.com/learn/understanding-linux-file-permissions

This file needs to be made executable `chmod +x installer.sh` command.

**Comment by KairusDarkSeeker** [comment]
@dishrex okay
