### ISSUE TITLE
Server crash with this error

### ISSUE THREAD

**Issue by FaanMaario** [Hydreon/Steadfast2#14]
Hi, My server crash and he generate a crashlog, 

Here, the crashlog:
PocketMine-MP Crash Dump Wed Sep 16 18:28:06 UTC 2015

Error: Uninitialized string offset: -1
File: /src/pocketmine/level/format/mcregion/Chunk
Line: 121
Type: notice

Code:
[112] 		unset($this->nbt->Data);
[113] 		unset($this->nbt->SkyLight);
[114] 		unset($this->nbt->BlockLight);
[115] 		unset($this->nbt->BiomeColors);
[116] 		unset($this->nbt->HeightMap);
[117] 		unset($this->nbt->Biomes);
[118] 	}
[119] 
[120] 	public function getBlockId($x, $y, $z){
[121] 		return ord($this->blocks{($x << 11) | ($z << 7) | $y});
[122] 	}
[123] 
[124] 	public function setBlockId($x, $y, $z, $id){
[125] 		$this->blocks{($x << 11) | ($z << 7) | $y} = chr($id);
[126] 		$this->hasChanged = true;
[127] 	}
[128] 
[129] 	public function getBlockData($x, $y, $z){
[130] 		$m = ord($this->data{($x << 10) | ($z << 6) | ($y >> 1)});
[131] 		if(($y & 1) === 0){

Backtrace:
#0 /src/pocketmine/level/Level(2668): pocketmine\level\format\mcregion\Chunk->getBlockId(integer 3, integer -1, integer 1)
#1 /src/pocketmine/Player(740): pocketmine\level\Level->getSafeSpawn(pocketmine\Player Player(10))
#2 /src/pocketmine/Player(720): pocketmine\Player->doFirstSpawn(boolean)
#3 /src/pocketmine/Player(1561): pocketmine\Player->sendNextChunk(boolean)
#4 /src/pocketmine/Server(2485): pocketmine\Player->checkNetwork(boolean)
#5 /src/pocketmine/Server(2222): pocketmine\Server->tick(boolean)
#6 /src/pocketmine/Server(2100): pocketmine\Server->tickProcessor(boolean)
#7 /src/pocketmine/Server(1701): pocketmine\Server->start(boolean)
#8 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/mcpe-1/PocketMine-MP.phar/, string /home/mcpe-1/, string /home/mcpe-1/plugins/)
#9 (1): require_once(string phar:///home/mcpe-1/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.6dev #0 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 2.6.32-37-pve #1 SMP Wed Mar 18 08:19:56 CET 2015 i686
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
GetInEffects 1.6 by TonyDroidd for API(s) 1.12.0
PopupAlerts 1.2 by EvolSoft for API(s) 1.12.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
NoVoid 0.3 by rirititi for API(s) 1.0.0
BasicHUD 1.0.6 by aliuly for API(s) 1.12.0
PurePerms 1.1.12 by 64FF00 for API(s) 1.13.0
BlockEffects 1.0.5 by GmWM for API(s) 1.12.0
TapToDo 2.2 by Falk for API(s) 1.0.0
WorldProtect 2.1.0 by aliuly for API(s) 1.10.0, 1.12.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
ChatDefender 1.1.1 by Falkirks for API(s) 1.6.0
CustomAlerts 1.5 by EvolSoft for API(s) 1.12.0
1vs1 0.0.2 by  for API(s) 1.0.0, 1.1.0
MSpawns 1.4 by EvolSoft for API(s) 1.9.0
HOLO 1.0.0 by Asparanc for API(s) 1.12.0
SimpleAuthHelper 2.0.3 by aliuly for API(s) 1.12.0
PureChat 1.2.8 by 64FF00 for API(s) 1.11.0
KillRate 2.0.0 by aliuly for API(s) 1.12.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtO2tv2zi2f4Vwi7vJhWVLfsXxbApk03SmuEmTO0m3wB0vClqibE4kUSNSSdzZ/vc955B6OclM
pu0u7ocJ2kA6JM/7RVL5tWdkKnqLYDIZTUZzfz7r9xKuzWlRqKK3+LVntjkM9zJlZCh6/V4qtOZr
BL3PZCaN5In8JCKmTSGzNVNxrIVZMC+AuXGZJG9kgpPzDS8Ww+Fwo1IxTMNceMHwUoU3wpzLTHjn
lwOcMdRFOMwJnAJ4mIhbkQxjVaTcwKpCrKXKhiebMruB+TmSsOj/wEJYlMAUEHkU9Hum4CDW4qfe
C589juQMf++NZrP5/oI1o8slDS+XlshyWVFZLomM92otzN8SmP822pOZEWtRsHGfVY9e0DwH+8DU
i+ABA5cJ34pi72DiP06aWCNCVzwWVzm/y/ba0+x65tAE/j7RGT1JZ7RLxw54ryL1RhbaWAorpRLB
M8I1fgpXMJ0FTyDTIoveiXtDaupgmzzAdiWKW8A2msynT2ALNyK8eSfMnSq6yKZPIoOfHWR2xHsF
Pt5FMnsSSeD7v4HkslAhBIoqOtgOnsIWHPjBE9i04YXpYJk/1HkdSHuT2eQJRB8/hiqDKC1D03GS
E5Xm3MhVIk4g8PWZ4hH4jFr9LELT72AqjUz0cnnOZXam1uvWLBf8zwzyen5n4uPQPCnXMtNDkvyQ
7aGaCvFLKQvxUWWh2PtjpJ9UHKaT/d4/Pvd74ptkvq9KS8CFlbu3iHmiRb8XqkggT0EwArRLszRl
BtT2XpqN1N6rbGW8V6+54fvfAZ4gGD856epmeybXG+MmTp6cSKmrPXX69FQJSj9RiSq0mzt7cu4P
AlGe89zNPPhtrBXCOU37TM+H8IwPI5+AeblKZMjiMgsNaJO10u7L+z57uYX/n/Z/pRWBo1YIUxYZ
U0VUkVzhEv0rLGF//SsLgn32T7b38hO+HODzy+1ny8po1LAyGlesTB5lRT/GCvyXkeOn0unzmWBH
LNwUe4jCsjProthwfbLh2Rr88ohBsAs766DF9Lxi+vA39Yfu9ECDY78ilwL+lv4imF0z7rcYn9nn
LXv1CuqcU+K4MoSM93Dsv2CIHR0dMR/IfP6zKv9Zlf+syn9W5boq93trkYmCJ1gCQW0aAhoSSDCY
ReIWWFiVMol6Cx/KZqGMChVMHE/6PZ5LmhaMBz5MW0sDr/4zf2BBwW8SucI1gwPCUGYcN0u9M5mV
9wzSCE82Shs2GswG45E3PvDyW8EgZ1ydX7IPkIPPOeSROfPni+BwMZ2xk9NrNvKDKZOz+QwQ4iZm
0ZvC8hG8fYIYhFfE5tvBj0pX5ABALwm91C2CRp18L8zb7DSOwez07tjsgPuN5kBxoJzSbKBiY5a9
Vtn2daFkFKGuSWs/odpGwAYARMbBD4EzrCf9XiRy4BMXwphWsXndBqQc25betcW3XLZ5sF6KnQ64
M0y6vLi6/nDx49lrAN2JlZYGud4Yk2vwGjDXplwNQpUOGwaHHZlAC5cqL/PjRBQdydvQfsdlUM8t
0U9vVXIFMnwzwVuUd8W9uj7+8fr95QNhQda7u7uBAFYQ68DcoGBXMs0TcQystuRqAbtiHQyCrmBN
ELFrwVMY1Bu13sgw/2aiNsxAPmsz9jvy7hi34XTYwgIaeKf+DiZvSe8ALcn9wbgjdSELaMyN7Mjo
f7mIFb7l0tJ+lgdnZZIA+3/jWoY/vH/dEqAGdY3nD2Zd48HOoky238xQFt1yuSmjLw5BnoifeRYV
CnC1krVXlQLoqSHFc21EMazFxPgsC3EpirQTnTWsqweUsquI2eTNG9/vKmL85Yr4aPFBn1Jx0Hr8
446LK534DRa0PDaYD9NxB7zrAdOu4N+nH86/mf0R2XLZJt99e54/X/P8Wr1WLYEqSEuW0WDUkeMN
T26+VTAanhsVqeWyofsMtj+oIomg8zMgaYv3DrhtjBG4of/74ejTpG8Tl3fIS255eW7R+Irw7IgO
GjqBJrY44+t1Sz0NbDdEd3RzBnulLLqIz08uT7+VoWvisJmixvcL8lWbr2EjDYq74UA1hlFRtCVu
gx/kpd4Dr5bFje4IPPtygWOHb7kMgYvIcYF71g5Pz/D2k1IblT7ohzrgrnDTf3ND1CYNEnUZ+aLO
KLjVQUs2em3LBJ630+bt+mXfefIXigS9iozlvYRUpDJxqxXuwy4y8XcNv55np3PatbdNVEG61pk8
wzqHXyGJJfpHks4jBvnh4uyiJQm97ta3nbRxrHNe8Cz8Zm6GRP9Id9a0mj+IJO9kggdD3fIAPefX
d2vtTv45nRsx8h9p3h5I75o4zEU7PRyBdrZXg/nvd3C/F3qtBvGBbiD30jmlhgLWe6KzQ76ap6/u
6wgJaOF/ZJL8yI1oaaEG7bqI/29o6Ks9HaSbLaA/51rLW3EaqkylCHBPx5dv4eV7lURXJuo99KUb
4LkAnv8j3lQr6DOeWEDIpwLAlXh0CDaAzgf8zEiBxxsvLus3dqKyWK4ZXqYsi2X2Ak9UrkTOghkL
5ovRwWIcsPfXJ3SighNSZaIj3EiGBY/Ngl2eMnvOhoOWmJerwhwFh8F4RCtEqoqtl8hUAtT3/XOE
3m1AdgBqc6TiGCE8y1SZhSgjHXDycCPFrUhFZvSRygg/ZlLPdXHgCEdjyxO/d4v00dQnXEmi7rw4
wYuQCr9dzDOZ8kR3gala1ZA1R4YjcUSIYlUARzXMzdnwIgpVUb/nt7njMJJxLMMyMdujgLDRoZpR
haeFMTJb6yME0zG2hw5+lKjVatvAtBBRawpekB29OTu+RpB1Y++XUhRbR8+BCnDLihl8HuTguNDy
Rkf/TT+gkdIoT/Nb4Rbi2VftVoNtmqBfMPRWFpJLlMA23lWgZzBQA+scKoKnsOuN0IJVcjFeCGY2
gkHoaHjghoVoUsNWgsksTMoIXEvijc2ORyKuK5XCyhgR7OLUPBZ9pmCk0IiSrQrBb9hWlYXDxWTM
wDzQLxAFsEwB/gFxCIjfibsa3RC6Pg620exOZX8xjOc59KwMVZOCsCF4zRbYZ3jdYuW+24iMlfm6
4BEgGCwz9HGLbLHM2IvrDcShlwAIuEh4ti75WjC8SSSVuXjQEt7pJFN+IqXi0hM8vrdSdBcCA1VC
ENngTt7IXESSD1SxHuLb8AyC5qOKP769uvg4Gx96o4+4DtRYI1qwZS8u+LKHhD5sBOqOGcXwAoKB
lO7AGcwE/YFOIHdEdpi0SZwCH/AkDJk0ErcyFGwDGSkhI6eA2IZGQxJzK4D1pjSRwqCyd7nIyznn
hVRnHKmzGIrOsvR9cchUyQoR2ZeUg9UGluVjDF+GyYFOuG3OY7eSs/9F34cpFANVNqxpv7jawDqO
HqwVcOpYsGbkDhErNTgo1ABwEpIckjnMhDoSoQ6bAQ+UsVK6Ee3FKUVbhQfFwSzAwJXBW5DV1ZY5
H4PpLjbr0QWjm2ayCaRsMDS4G48i0IG2Xols4iUKsMM1VEXMfQx8cSVQH2AQ8UvJEzTVGqpSxm55
Ugq250hCjt4H5JYe5ASBedgDS+ONxQJGkfK7Ml3h/UXMjvU2C6+5vmF4gwTBNcDx9xo0gr5bCYmz
NgVUvRLcBWbrPqO9NHOpDdy5D2pIQWsaizOpBWobwtIyg6jCKYT7itwJ5IHAK9Q9JGIjQAUgDoVB
VrOGWrXsvI0xenEKRmmfSfMX0JwpaFUksA6Qh+6sZXsgAdiZjVAjJIPnpFywAMPYViUK4u8hBYNW
sRFgFsyoWGGySsWar7YGuGFXlg+fKEuNtrUpAAS6k8QVaZph6XFFz4E0KSWW4CuQvyCxZ4QqhuRR
UbS2B0lK8ti1AiEURiMqDOisiUlbRUGEEfRhlEYoYxtIQzz6fy4BtkgV/wePsY9V9avYh21vThy4
RFZz5LBpBkGFlRFyjuMHaVZMOZagKZaKKhWGokZqdNVasVaHWwB0INNE6GI0w8OWzwYaZXiVQf6C
AAW1YXJ4SqtWm9AQJZT8MdTttCXVYsQBwdcEss1GSOECMwgWP5o+eDgZZXbNL+gvFyHWSE06QV6t
gu3aWgBQo8h1I+bYd3Lq/UcZclKPrdRrXqzA/F6oksQ2aRhjj2qVvAlZcWuYWwOhm/KspGrc5gI6
lRIcYb9fpYQdT3CuYNMqnboS9rRxsQG7sKWQ3sAdNqpMopoRCQnkLmMN6+i2LCfOQcCZ77yWvXhD
gfAgNZKv2NW1UHGh0irD4lo37rWTUsumIIQz3a4rPOI/rXXYA4f4XYG2+j4jl8d8SEDkDPcgKA2z
vXKforOA3kTbSR62B9jmNLgQVWVmFyWjSgevlV22az6sAdhE2WVtDJaKm/YNZKY65IWwURBWaucL
FSEcqIv3b6JaZpn9kKLu6sA1ElsIV9zATgT7EI4NsMavV5hLSRSAtmd1ozYTrURdEinXvGjnrmoE
A7/YGsTdZ17QcmYsfUTWMxUroPjpzGaVptTSHgHrXGRznTOgXQtAx9OA/QAbIVDvEbTJ4Lgnl+/7
sBY4WEH+uZOR2dikTfFdo/cIPTi+6wuajkGTYlpTB+w4gnja8CQeQv9vm5hIgJ85QkDS+p/K2gFZ
F+cWrla7dY+xh00QT/o2rpHuB5lBgwlSgdcI8mys9O8vs8uqT2i6eWyBcNEd5PkltvJZ7rnXdkcG
GzexKtcL13K8YviNknFVBXtKGq76SU1pbCOqPnPpLEGtRdUlajbUhpsS/GW4Dq1mIa1FuvG6asfX
2VCIqoNk9vsqu5Wiqc65UFoydwgqNORfbolnlyxY/UmWlYeOPZDbWzwTtimJd/BD3sStmmmRB12a
h9xQhJLhXry7uD5dMMq58C8soX/PYNdFiOiACy1H7DnKNXt1H3zcMVZIX9VVspIPUUECTtBnDPrN
yHcFBBOZrUvoRLi7RbgrRs6DuuC6efJ9F5K2Eq64Fi1qewHEySNk+mwEA8FjA8KEg32KWS3abJA7
XCNm3HS5IwomIC9Zelj5rSlpe9vsezEP0B4IeyfMBjy541ttcTs8LeftpG/yo+NUlVk7/2vXsVVM
IPuIDTcMkJrxccEmTy/lBUAjy7vF0S06bnvxYDF5VybsBnMlLLKViDEP0eEL5iu0Qo3UHsm0El9g
zcVvoeRia1d9FByqfOvODFwlqtsZyhMxHY9VSdElsbhMaJrS4KoeRqgMbSGh/VeBG3XwC0Bbaepn
hdsgGxuap+gqKWVKLC+1+FVMW1OgOitTnPN7xnfVktvP5ETUeEPHElbmH3kkS91a5qzAHXMUo3ap
8zqcbzM2nX15ZR6BJza+wkK8prN+hPvrXcabTV3F++Ah8y773XFJ+3PYi5fCmdetp6gnuKfBVgs2
/yJsucrLxGFzz1iXdhAvM4pID7SHTNsTPo/cCASfULSn+AUgHsU4aOCyA56ILZjt7CqL4veGZb5g
h7bds/5IucN2GQ6Xxm0MvrsjRUA6xdc7joRqIMF4upLg+HaKO4yz+/OFTUV4lFBwvWEWaguscxLr
vK6Nb85ZYI2HBz9dSF1NOtB8k8ssVo0b4Cd1C0ty0DoHhC6I+MtUtk2xx6cA0aBfXTOKmxY3zJph
Yhi/UGZ8vYbi4w4G6iMXbBDxk+Obx6Wx/CA6/Rg/qC/rymTi3dXgE3Z0YQ1QZJ4rzU37R1CVtw6L
TvAskQ63RKJyLFZ9eAcJ8OTOVH0YtCUxtMkClA3lKcMqj5NcZS3ROhCPLSTM3VK0OogSuk1tbH2r
8p3DhhaywxV+vaMUvAx8RCWJhGJjrXJ6z7Hc2hdsVwC/Y2JRcUND4Oy4R16wn/DRgxLTp03zPxCj
TYJVF9I+hSUhqs2C3bFVx9q0FXvsUJd2tlTDNDUMKHYKfYQERl2Fb7FOVIkBemJ4Co6hSwWpobZg
eBS+GH130J8e3gf98f24P/ou+C6COmyz1h5ejISYYY7mPluDf2v7Npnu06G3uDciQ4XQvfAJlKHW
x6ER3TzVr1AN1vWfh+QhTnUv+pdEGjG2n6169gvZT/Y71hHdS61CaGs2zd+W8AQihxcNwP7lS/VW
Fkn9EsvE4F0poA7spyCxyevRddo8byB67dUvTPpZ19eDeFWfruwZbz0ZWsJtbhoJDEeGopa4V5dn
RBWf8xBauWbtFgSm72bdE5sOkDuUnHl4NzTyp/4YHl++BbvF44Ox4NMomk7H84NZMPFnfO6PRnyy
mvPxwWQSzFejiS/YS6B0uUG10IUeEVZa3jdKdzt1NyFAQX8UsdtmApTozcU0Djk0qhMg68cHB+HB
fD6bToH0+HA0FmN/dXhwGEVET29S1ahQU2DprqTSKh8mG3UjMqgzRQ35IPgNZASrKPqwY8vp8qT6
hOWTzO3biD4s+D9M7ReXVFoAfgBSTFBtb057nz//CxyFy9Q=
===END CRASH DUMP===

I hope you can do something :)

**Comment by tntloverlol** [comment]
Could you see if you get the crash when you have no plugins enabled?

**Comment by FaanMaario** [comment]
If I remove all the plugins, There is again this crashlog

**Comment by tntloverlol** [comment]
Pastebin the new log.
