### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by Muqsit** [Hydreon/Steadfast2#150]
Commands don't work. Is there a possible fix to this?
Whenever you type a command, you are greeted with an " Unknown command... " message.

**Comment by Guillaume351** [comment]
You have to create a commands.json file in your plugin - you can see an example here : https://gist.github.com/NiclasOlofsson/db712fd9e3c9cb0777cd9381cb48915a

**Comment by Muqsit** [comment]
Thanks =D
