### ISSUE TITLE
Commands not working!!

### ISSUE THREAD

**Issue by EpicArtz08999** [Hydreon/Steadfast2#154]
Non commands work, not even SimpleAuth plugin works.

**Comment by Guillaume351** [comment]
You have to create a commands.json file in the root of your plugins, example here : https://gist.github.com/NiclasOlofsson/db712fd9e3c9cb0777cd9381cb48915a

**Comment by EpicArtz08999** [comment]
bruh doing that for every single command! that is just stupid

**Comment by Guillaume351** [comment]
It's not Steadfast2 choice, it's how MCPE 0.16 is made : it has to receive all available commands in a json format in order to work. Please close issue, thanks

**Comment by EpicArtz08999** [comment]
Genisys doesnt use json.......... and OK

**Comment by hlogeon** [comment]
@EpicArtz08999 
Genisys DOES NOT support MCPE 0.16

**Comment by EpicArtz08999** [comment]
I mean here ---> https://github.com/H4PM/Elywing
