### ISSUE TITLE
Bug: Serialization of "Closure" not allowed

### ISSUE THREAD

**Issue by MyNameIsTriXz** [Hydreon/Steadfast2#160]
When I want to use a Synapse extension, ported to my Core plugin, it shuts down with this:

Fatal error: Uncaught Exception: Serialization of 'Closure' is not allowed in [no active file]:0
Stack trace:
#0 {main}
  thrown in [no active file] on line 0

With some debugging I found out that pocketmine\Thread causes it, exactly Thread::start() causes it...

I use the latest version, downloaded from GitHub on my 512 RAM VPS server.

**Comment by xZeroMCPE** [comment]
SteadFast is really old, and still uses the 1.4 base (Mostly what makes it faster then any other Server Sofwares, Since alot of things are removed such as player data, etc) . Alot of codes needs to be changed into  Synapse extension itself, to add support for SteadFast

**Comment by Guillaume351** [comment]
You can fix this issue by removing a few lines of the plugin BUT even if you'll spawn, other players won't see you moving as SteadFast use a different method to dispatch packets.

I think you should close this issue as it's not related to SteadFast but Synapse which is not made for SteadFast  (even if I would like it to work with it :/)

**Comment by MyNameIsTriXz** [comment]
Oh, I didn't know that, I thought it doesn't have big differences to G*nisys. So I should try the new Proxy, written by the Lifeboat team, does anyone have success with it so far?
