### ISSUE TITLE
How to use transfer

### ISSUE THREAD

**Issue by tigerza117** [Hydreon/Steadfast2#169]
Lbsg work transfer proxy
how to use transfer proxy

**Comment by Driesboy** [comment]
yeah

**Comment by iMOEchan** [comment]
May You need a specific plugin

**Comment by Driesboy** [comment]
NO YOU MEAN

**Comment by dishrex** [comment]
Steadfast2 only comes with the classes to allow a proxy to work (like using the proxy instead of raklibinterface), the proxy is not included.
