### ISSUE TITLE
Problems when switching worlds

### ISSUE THREAD

**Issue by Renual1337** [Hydreon/Steadfast2#179]
When you switch from one world to another, it sends chunks that don't exist and spams your screen with it for like 10 seconds before they fade out.

**Comment by NemanjaMAX** [comment]
@Renual1337 Its cannot be fixed,this actially aren't issue.
Cuz speed of loading is asymc workers (cpu) and example u have 2 cores,its be ok ;D

**Comment by SpaneBoswell** [comment]
It's just chunks unloading, you can't get rid of it, all custom pmmps have it, 

It's new in 1.0.4,

This bug was created surrounding it, Mojang fixed it, but now chunks unload somewhat slowly

https://bugs.mojang.com/browse/MCPE-19818
