### ISSUE TITLE
Error when loading or generate level with anvil format

### ISSUE THREAD

**Issue by vzlomka76** [Hydreon/Steadfast2#184]
**Version: https://github.com/Hydreon/Steadfast2/commit/093aa74ff6c0a4517f404c1341c0359a7155973a**
`[08:06:09] [Server thread/CRITICAL]: TypeError: "Argument 5 passed to pocketmine\level\format\generic\BaseChunk::__construct() must be of the type array, string given, called in /home/anton/steadfast/src/pocketmine/level/format/anvil/Chunk.php on line 92" (EXCEPTION) in "/src/pocketmine/level/format/generic/BaseChunk" at line 49`

**Comment by DanilZz** [comment]
this core can't generate world

**Comment by caspervanneck** [comment]
and load @DanilZz

**Comment by dishrex** [comment]
Anvil is currently not supported on Steadfast2
