### ISSUE TITLE
Incorrect encoding of NBT network strings causes invisible signs issues

### ISSUE THREAD

**Issue by dktapps** [Hydreon/Steadfast2#187]
NBT network strings as of 0.16.0 are uvarint-prefixed, but your implementation uses bytes. This causes invisible signs issues when signs have lots of Unicode text on them. The issue is rare, since the sign text has to be more than 127 bytes, but it does exist.
https://github.com/pmmp/PocketMine-MP/commit/06f0534d653f6f5f57acabad1f017457fe3d924b
 
I would open a PR, but your implementation of varint for NBT and BinaryIO is confusing to me. (No offence :wink:)

### References
https://github.com/Hydreon/Steadfast2/blob/master/src/pocketmine/nbt/NBT.php#L644
https://github.com/Hydreon/Steadfast2/blob/master/src/pocketmine/nbt/NBT.php#L654

**Comment by remotevase** [comment]
What a surprise, they don't  care.

**Comment by SuperMaXAleX** [comment]
@vchibikov Don't close this
This is a real existing issue

**Comment by vchibikov** [comment]
resolved https://github.com/Hydreon/Steadfast2/commit/1485030728eff4bb32957da6b56ad0d442b958df
