### ISSUE TITLE
*PLEASE ADD THE PHAR IN RELEASES*

### ISSUE THREAD

**Issue by MateiGamingYTB** [Hydreon/Steadfast2#188]
but the src don't work on the server, please resolve or give the phar pls

**Comment by BukkitPlaysMC** [comment]
https://github.com/Hydreon/Steadfast2/issues/172

**Comment by dishrex** [comment]
Why are you yelling? We do not create phars, src will work wherever the devtools plugin is running. You also use DevTools to create phars (http://forums.pocketmine.net/plugins/devtools.515/).

**Comment by MateiGamingYTB** [comment]
But dont work !!!!

**Comment by MateiGamingYTB** [comment]
5 Min for profe

**Comment by Guillaume351** [comment]
@MateiGamingYTB Try harder... It does work. If you get the server to run, you just have to run a simple command. If you can't get it to run, maybe Steadfast is not adapted to your server anyway (a lot of current PocketMine plugin won't be compatible)

**Comment by MateiGamingYTB** [comment]
Man i join server and he crash....!!!!

**Comment by xZeroMCPE** [comment]
@MateiGamingYTB  Don't use something if you don't understand nothing about it.....

Stop spamming issues! with useless topics...


Lock this already... this kid is just....

**Comment by MateiGamingYTB** [comment]
But resolve problems and me done with issues spaming
