### ISSUE TITLE
Can you please remove The Commands.json

### ISSUE THREAD

**Issue by KamiPlayzYT** [Hydreon/Steadfast2#192]
I have 3 Commands to Use but i whan to use all Commands (Transfer,gamemode,etc.)
Use The Code in The Genisys Software or Elywing thank you :)
![screenshot_2017-02-01-19-03-36](https://cloud.githubusercontent.com/assets/22433576/22555046/ada44872-e962-11e6-99d5-1861e616c991.png)

**Comment by caspervanneck** [comment]
yes plz

**Comment by Frago9876543210** [comment]
yes, this uncomfortably

**Comment by kenygamer** [comment]
@KamiPlayzYT Many want to do this. It could be an option this to have to register the commands manually.
