### ISSUE TITLE
Error - Ubuntu Linux Server

### ISSUE THREAD

**Issue by lolmanz0** [Hydreon/Steadfast2#194]
I installed binaries on Ubuntu with installer.sh but when I want to start it, it shows error: 
./bin/php7/bin/php: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory

**Comment by dishrex** [comment]
This is a product of a new php version I believe. 
run `sudo apt-get install libltdl-dev` and see if that works. 
I will look at adding that to the installer script too.

**Comment by lolmanz0** [comment]
Server started but I have this error: Failed loading /pocketmine/bin/php7/lib/php/extensions/debug-zts-20151012/opcache.so:  /pocketmine/bin/php7/lib/php/extensions/debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory

**Comment by lolmanz0** [comment]
And also after load in console: [Server thread/WARNING]: Non-packaged PocketMine-Steadfast installation detected, do not use on production.

**Comment by vchibikov** [comment]
It's not exactly an error. Steadfast don't use opcache. So, you may comment line with opcache in php.ini if this message bothering you.

**Comment by vchibikov** [comment]
Second. It's just warning. It informs you, that you should use phar archive instead of source code of steadfast if you want use it on production.
