### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lolmanz0** [Hydreon/Steadfast2#195]
Server started but I have this error: Failed loading /pocketmine/bin/php7/lib/php/extensions/debug-zts-20151012/opcache.so: /pocketmine/bin/php7/lib/php/extensions/debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory

**Comment by NFGamerMC** [comment]
How do I install

**Comment by vchibikov** [comment]
It's not exactly an error. Steadfast don't use opcache. So, you may comment line with opcache in php.ini if this message bothering you.
