### ISSUE TITLE
Cannot Type Commands

### ISSUE THREAD

**Issue by ghost** [Hydreon/Steadfast2#198]
So I am op but when I type commands it says unknown? Also when I started the server it got mad and said error because of the world format that was working with pmmp

**Comment by kaitododoyt** [comment]
Visit my channel, tutorial for this build

**Comment by NFGamerMC** [comment]
Sure, what is your channel or is it on your GitHub profile?

**Comment by kaitododoyt** [comment]
Is "kaitododo" on YT

**Comment by NFGamerMC** [comment]
Okay, but I cannot find the vid only some other pocketmine stuff

**Comment by vchibikov** [comment]
What command you trying execute? May you give a link on world you used?

**Comment by SuperMaXAleX** [comment]
There is only 3 commands. 
/help
/version
/about

**Comment by asyven** [comment]
have this "problem" too.
can anyone help me?
