### ISSUE TITLE
Player new Packages [Critical]

### ISSUE THREAD

**Issue by EpicArtz08999** [Hydreon/Steadfast2#200]
Please add $player->sendTitle();
            add $player->sendSubTitle();
Thank you for you're time.

**Comment by dishrex** [comment]
The `SetTitlePacket` is in the 1.0.5_beta branch and will be merged into master soon. We will probably create some sort of send wrapper around the packet when we start using it. If you would like the functionality sooner feel free to add it and make a pull request.
