### ISSUE TITLE
Join "Building Trrain" Very slowly

### ISSUE THREAD

**Issue by tigerza117** [Hydreon/Steadfast2#201]
i am set hige and Join "Building Trrain" Very slow

![image](https://cloud.githubusercontent.com/assets/13928985/24610730/ed5d1504-18a9-11e7-96ff-0224fc0f4637.png)

**Comment by G2PCraft** [comment]
He mean "he set high Render Distance and when he join the server it use very long time to join at Building terrain.".

**Comment by SuperMaXAleX** [comment]
Normally lol
It charges chunks
