### ISSUE TITLE
Titles

### ISSUE THREAD

**Issue by EpicArtz08999** [Hydreon/Steadfast2#205]
How can I send Titles?? I tried different methods but nothing. how did you guys did it on lbsg.

**Comment by vchibikov** [comment]
It is necessary to send packets in a certain order.

First must be TITLE_TYPE_TIMES. It contain times for TITLE and SUBTITLE and may contains empty text field.
Second, if you wish text with subtitle, you must send TITLE_TYPE_SUBTITLE.
Third, TITLE_TYPE_TITLE finally.

Title and subtitle may not contains time at all.

This is the only sequence which works for us. And yet we don't find method to display subtitle without title.

**Comment by xZeroMCPE** [comment]
@vchibikov 
send title " ". In other words, send title as a space.

**Comment by vchibikov** [comment]
What do you mean?

**Comment by BukkitPlaysMC** [comment]
https://github.com/Hydreon/Steadfast2/blob/master/src/pocketmine/Player.php#L4068

**Comment by EpicArtz08999** [comment]
nvm it was that it wasnt showing on player join even, lol ama close this

**Comment by xZeroMCPE** [comment]
@vchibikov Send titles as nulled, send subtitles with something you want. It'd work!
