### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by kek228** [Hydreon/Steadfast2#214]
Title packet not works :c

**Comment by BukkitPlaysMC** [comment]
How does it not work? Please explain what you did. It works for me/us.

**Comment by kek228** [comment]
i copied sendTitle method from pm. 
did some changes (names of constants)

**Comment by BukkitPlaysMC** [comment]
https://github.com/Hydreon/Steadfast2/blob/master/src/pocketmine/Player.php#L4097-L4119
