### ISSUE TITLE
Hello, request to join

### ISSUE THREAD

**Issue by RateekMCPE** [Hydreon/Steadfast2#219]
I am a French developer, I would like to offer my help if possible

**Comment by Guillaume351** [comment]
@RateekMCPE Hello,
You can already create pull requests, issues are not made to ask to join the team.
If you want to contribute, you can finds bugs & report them here.

**Comment by RateekMCPE** [comment]
D'accord, j'aurai jamais crue que toi en personne tu aurai répondu 👍  ! 
Merci de m'avoir au moins répondu ! :)
