### ISSUE TITLE
Command Plugin Not Working? 

### ISSUE THREAD

**Issue by StormCraftMCPE** [Hydreon/Steadfast2#228]
Please Fix

**Comment by MCNationPE** [comment]
src/pocketmine/command/Command.json

**Comment by kenygamer** [comment]
@MCNationPE Fix:
To add the command go to *src/pocketmine/command/commands.json* and add them there.

**Comment by sftpocketmine** [comment]
@kenygamer I know the correct file for this, but could you explain/give an example of the format you'd use to add a command to it?  The format it shows is extremely confusing...
