### ISSUE TITLE
How to command.json have all command ?

### ISSUE THREAD

**Issue by pokiwar111** [Hydreon/Steadfast2#229]
help I ! I can't create command.json have all commands .

**Comment by vchibikov** [comment]
What means "all commands"?

**Comment by pokiwar111** [comment]
How to I can have a file command.json have command for a plugin

**Comment by kenygamer** [comment]
@vchibikov He asks how to add a command from his plugin to the *commands.json* to register it. He probably does not handle this type of file and does not know how to add it.
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by vchibikov** [comment]
After commit https://github.com/Hydreon/Steadfast2/commit/991c007c707194add2b80ee4219d8b138662553f commands logic was changed. Now if you don't want use commands.json just don't create it in your plugin.
