### ISSUE TITLE
trouble with loading worlds

### ISSUE THREAD

**Issue by asyven** [Hydreon/Steadfast2#230]
![d0e4ef2736](https://user-images.githubusercontent.com/10788200/27244702-68d1f17a-52f0-11e7-905d-6ab6a370b7c2.png)

I was try to load world, and get this notice, can you help me?
(The worlds are already droped in the "worlds" folder)

**Comment by kenygamer** [comment]
@asyven What if *level.dat* level's name is different than folder's one?
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by asyven** [comment]
@kenygamer yes, you answer its true
How i can change worldname on Level.dat?

**Comment by kenygamer** [comment]
@asyven What about using **ManyWorlds** plugin , subcommand "fixname"?
Please let me know if I've helped you
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ
