### ISSUE TITLE
Slapper don't save

### ISSUE THREAD

**Issue by RompeCraneos** [Hydreon/Steadfast2#233]
Slapper Human isnt saving in the map, only mobs and other entities as FallingSand are working after reset

**Comment by vchibikov** [comment]
What is a Slapper?

**Comment by vzlomka76** [comment]
@vchibikov It's a Human with custom settings

**Comment by jojoe77777** [comment]
@vchibikov https://github.com/jojoe77777/Slapper

**Comment by DarkYusuf13** [comment]
Convert your slapper plugin to .zip, find SlapperHuman and edit the codes getLoaderId() to getId() .  and save make plugin .phar and try, It will be fixed
