### ISSUE TITLE
Help For command.json

### ISSUE THREAD

**Issue by TestV2** [Hydreon/Steadfast2#242]
Hello
If you can define the command.json for a plugin instance or delete it?
For example Mspawn

**Comment by vchibikov** [comment]
Why you don't like `command.json`?)

**Comment by MrSmileCH** [comment]
I think it would be simpler an option in the pocketmine.yml or pocketmine-soft.yml to enable or disable

**Comment by TestV2** [comment]
I do not know how to enable it
You were correct about the film about it
For example, how can I enable Slapper plugin?

**Comment by TestV2** [comment]
If it can be disabled through pocketmine-soft.yml, it will be great
Both for the server and for the plugins

**Comment by vchibikov** [comment]
After commit https://github.com/Hydreon/Steadfast2/commit/991c007c707194add2b80ee4219d8b138662553f commands logic was changed. Now if you don't want use commands.json just don't create it in your plugin.
