### ISSUE TITLE
Plugin Commands not registering

### ISSUE THREAD

**Issue by sftpocketmine** [Hydreon/Steadfast2#246]
when i look in console i have every command visable and working but when i log in as a player they all say unknown command. Any help on this?

**Comment by sftpocketmine** [comment]
and i mean without me having to add all the commands to commands.json

**Comment by junkdude** [comment]
ur dumb u have to

**Comment by sftpocketmine** [comment]
Grrr, well @junkdude @alleskos @kroer @vchibikov could one of you at least explain / give a simplified example format that you'd use to add commands to the commands.json file? I've tried MANY different ways and none of them have worked :/

**Comment by MrSmileCH** [comment]
It would be very helpful to put the plugin commands as an example

**Comment by vchibikov** [comment]
```
"command_name": {
        "versions": [
            {
                "description": "This is command description.",
                "permission": "any",
                "aliases": [],
                "overloads": {
                    "overload_name": {
                        "input": {
                            "parameters": [
                                {
                                    "name": "param_1",
                                    "type": "rawtext"
                                }
                            ]
                        },
                        "output": {
                            "parameters": []
                        }
                    }
                }
            }
        ]
    }
```
It working example of command, NOT whole file. I mean it won't work if you copy paste it.

File contains associative array (map, dictionary) of commands, so they SHOULD be framed with curly bracket.

```
{
    <command 1>,
    <command 2>,
    ....
    <command N>
}
```
Here <command i> is command description from first code example.

**Comment by vchibikov** [comment]
After commit https://github.com/Hydreon/Steadfast2/commit/991c007c707194add2b80ee4219d8b138662553f commands logic was changed. Now if you don't want use commands.json just don't create it in your plugin.
