### ISSUE TITLE
Edit me about the world of the server

### ISSUE THREAD

**Issue by hachkingtohach1** [Hydreon/Steadfast2#248]
How do I extend the world to my server?

**Comment by vchibikov** [comment]
What do you mean?

**Comment by MrSmileCH** [comment]
I think it refers to that the phar the mcregion and not anvil like the other versions of other phar

**Comment by vchibikov** [comment]
Your version i also don't understand)

**Comment by SuperMaXAleX** [comment]
I understand : He wanted to say — "How can I generate a world directly from the server?"

**Comment by vchibikov** [comment]
File server.properties. Set auto-generate value as "on".
