### ISSUE TITLE
Place blocks

### ISSUE THREAD

**Issue by RompeCraneos** [Hydreon/Steadfast2#249]
Cant place blocks in creative :/

**Comment by MCPEATECH** [comment]
are you sure? Have you tried placing an item in the hotbar or reloading your game, this error does not occur for me!

**Comment by RompeCraneos** [comment]
maybe windows 10 problem?, i can place only in survival with /give, missing block in creative mode when i tried to place blocks. Sorry my english

**Comment by MrSmileCH** [comment]
The same thing happens to me in creative

**Comment by vchibikov** [comment]
What is block id? OS of your device? And also check your spawn protection radius.

**Comment by RompeCraneos** [comment]
@vchibikov Is W10 UI Problem, i changed to pocket ui and problem disappears... And with normal W10 UI i can place blocks in survival with /give command

**Comment by vchibikov** [comment]
Corrected. Try it.

**Comment by SuperMaXAleX** [comment]
Fixed for me.

**Comment by RompeCraneos** [comment]
Fixed, Thanks ;)
