### ISSUE TITLE
Does it affect anything?

### ISSUE THREAD

**Issue by MrSmileCH** [Hydreon/Steadfast2#251]
Notice: Undefined index: name in /home/minecraft-pe/server/src/pocketmine/network/protocol/AvailableCommandsPacket.php on line 86

**Comment by vchibikov** [comment]
This means that one of your commands has the wrong syntax. Namely, you did not specify a name for one of the parameters.

**Comment by MrSmileCH** [comment]
Is there any way to unlock all the commands and even the plugins without being put one by one in comands.json, it is a bit complicated for all those who have too many plugins on a server

**Comment by vchibikov** [comment]
For current moment, no.
