### ISSUE TITLE
 Color text bug?

### ISSUE THREAD

**Issue by MrSmileCH** [Hydreon/Steadfast2#252]
I can not write in color in chat nor in signs
![sin titulo](https://user-images.githubusercontent.com/27845246/28389072-5a2b6e9e-6c9a-11e7-860a-216f492b4157.png)
![sin titulo1](https://user-images.githubusercontent.com/27845246/28389078-5e349452-6c9a-11e7-9a11-cb925ce65c56.png)

**Comment by vchibikov** [comment]
Class Player has field removeField. It's flag prohibit to player use colors. It true (prohibit) by default. So you need set it in false (allow) (using setRemoveFormat method). You may set it on PlayerLoginEvent.
https://github.com/Hydreon/Steadfast2/blob/master/src/pocketmine/Player.php#L260
https://github.com/Hydreon/Steadfast2/blob/master/src/pocketmine/Player.php#L470

**Comment by MrSmileCH** [comment]
Thanks :)
