### ISSUE TITLE
I have a small inconvenience

### ISSUE THREAD

**Issue by MrSmileCH** [Hydreon/Steadfast2#253]
I pass on my server that is left in the inventory after executing a command / hub that takes the function of cleaning the inventory, But disappear when touching the ground with the item that had remained in the slot, as well as the armor

**Comment by SuperMaXAleX** [comment]
I can confirm

**Comment by MrSmileCH** [comment]
Is a bug of the version, right?

**Comment by SuperMaXAleX** [comment]
Of Steadfast, yep

**Comment by MrSmileCH** [comment]
Have you solved it?

**Comment by BI0MER** [comment]
I know this bug, you should after cleaning do $player->getInventory()->sendContents($player); 
аnd for the armor slots $player->getInventory()->sendArmorContents($player);
P.S. This is not exactly a bug version

**Comment by MrSmileCH** [comment]
The plugins I bring to
The function that cleans the inventory:
   $player->getInventory()->clearAll();

The function to add items to the inventory are:
    $player->getInventory()->addItem(Item::get(318, 0, 1));

The function to add armors are:
   $Item = Item::get(306, 0, 1);
   $player->getInventory()->setHelmet($Item);
   $Item = Item::get(307, 0, 1);
   $player->getInventory()->setChestplate($Item);
   $Item = Item::get(308, 0, 1);
   $player->getInventory()->setLeggings($Item);
   $Item = Item::get(309, 0, 1);
   $player->getInventory()->setBoots($Item);

**Comment by BI0MER** [comment]
@MrSmileCH After all your functions, execute the code I've specified
Example:
$Item = Item::get(306, 0, 1);
$player->getInventory()->setHelmet($Item);
$Item = Item::get(307, 0, 1);
$player->getInventory()->setChestplate($Item);
$Item = Item::get(308, 0, 1);
$player->getInventory()->setLeggings($Item);
$Item = Item::get(309, 0, 1);
$player->getInventory()->setBoots($Item);
$player->getInventory()->sendArmorContents($player); //changing only the armor slots

or to clean inventory:
$player->getInventory()->clearAll();
$player->getInventory()->sendContents($player); //armor slots not cleaned
$player->getInventory()->sendArmorContents($player); //now cleaned
