### ISSUE TITLE
Teleport function

### ISSUE THREAD

**Issue by BI0MER** [Hydreon/Steadfast2#257]
Not working yaw and pitch parametrs in teleport() function (Player class)

**Comment by MrSmileCH** [comment]
Did you add this to commands.json?

"tp": {
        "versions": [
            {
                "description": "Teleports the given player (or yourself) to another player or coordinates",
                "permission": "any",
				"show-in-help": false,
                "aliases": [],
                "overloads": {
                    "byPass": {
                        "input": {
                            "parameters": [
								{
									"name": "param_1",
									"type": "rawtext"
								}
							]
                        },
                        "output": {
                            "parameters": []
                        }
                    }
                }
            }
        ]
    }

**Comment by BI0MER** [comment]
Heh, teleport function in Players class (https://github.com/Hydreon/Steadfast2/blob/master/src/pocketmine/Player.php#L3029), not command

**Comment by MrSmileCH** [comment]
Does it give you error in console?

**Comment by BI0MER** [comment]
@MrSmileCH Nothing, these parameters do not set the player's position on yaw and pitch

**Comment by BI0MER** [comment]
Can you watch the code? There is not implemented, only the parent construction...

**Comment by BI0MER** [comment]
I'm fix this with $player->sendPosition($spawn, $spawn->getYaw(), $spawn->getPitch(), MovePlayerPacket::MODE_RESET);
But this is not very correct as with the clearAll function
