### ISSUE TITLE
 I have an important doubt

### ISSUE THREAD

**Issue by MrSmileCH** [Hydreon/Steadfast2#261]
There is a registry plugin that works for me, I have already searched and they have not worked for me

**Comment by BI0MER** [comment]
Which works for you?

**Comment by MrSmileCH** [comment]
Do not know where you could find one that is compatible for this version?

**Comment by BI0MER** [comment]
for version mcpe 0.15 - 0.16

**Comment by MrSmileCH** [comment]
The logging plugin to work in version 1.1.x has to be version 0.15 or 0.16?

**Comment by BI0MER** [comment]
Hah, version is just a number. Almost everything depends on the api core

**Comment by MrSmileCH** [comment]
I have all the necessary plugins, the only thing I lack is a login plugin and I have not found any

**Comment by BI0MER** [comment]
SimpleAuth - github.com/PocketMine/SimpleAuth?
ServerAuth - github.com/EvolSoft/ServerAuth?
AuthMe - github.com/Edwardthedog2/AuthMePE?

**Comment by MrSmileCH** [comment]
ninguno me funciono, serverauth requiere esto : 
[16:49:01] [Server thread/CRITICAL]: ReflectionException: "Class ServerAuth\CraftItemEvent does not exist" (EXCEPTION) in "/src/pocketmine/plugin/PluginManager" at line 741

simpleauth 
Does not let the command / register {password}

authme Does not let the command / register {password}
