### ISSUE TITLE
World bug

### ISSUE THREAD

**Issue by xISRAPILx** [Hydreon/Steadfast2#266]
![image](https://user-images.githubusercontent.com/28113262/28725528-62e2697e-73c6-11e7-9fb5-fce3716867ac.png)

**Comment by BI0MER** [comment]
Формат мира какой?

**Comment by xISRAPILx** [comment]
default-format: mcregion @BI0MER

**Comment by BI0MER** [comment]
File server.properties set auto-generate value as on
