### ISSUE TITLE
 Is it possible to add another type of ban?

### ISSUE THREAD

**Issue by MrSmileCH** [Hydreon/Steadfast2#267]
As shown in the picture

![sin titulo](https://user-images.githubusercontent.com/27845246/28733250-c97bbd1e-73a0-11e7-95bf-45ff55d5aaa7.png)

**Comment by BI0MER** [comment]
You can, but you need a criterion (ip, cid, name) by which you will block

**Comment by MrSmileCH** [comment]
It would be a good idea to insert another type of ban and not just the ban-ip or ban-player

**Comment by BI0MER** [comment]
Call this ban parametr by which the ban will occur

**Comment by MrSmileCH** [comment]
Was an idea that I hope to someday implement, I can not do it for reasons other than php, but from what I've seen its server version is the most stable and does not go lag like genisys, tesseract or pmmp versions

**Comment by hachkingtohach1** [comment]
No add command , you can add a plugin ban

**Comment by SuperMaXAleX** [comment]
That’s useless. MC:PE 1.2 will have XBOX Live authentification soon.

**Comment by BI0MER** [comment]
@SuperMaXAleX  It is unlikely that many will use it

**Comment by MrSmileCH** [comment]
That think about the update of all united, consoles, movil, pc, more than anything I mean that happened with the other servers not so recognized

**Comment by dishrex** [comment]
MCPE 1.2 will not let you connect to a remote server unless you are authenticated with XBL. No need for another type of ban.

**Comment by BI0MER** [comment]
@dishrex Really? It so greatly!
