### ISSUE TITLE
W10 Item Dropping Issue

### ISSUE THREAD

**Issue by junkdude** [Hydreon/Steadfast2#268]
If you try to drop an item on w10 with the q key, it drops all the items in the slot if its more than 1.

**Comment by BI0MER** [comment]
Fix this - https://github.com/Hydreon/Steadfast2/pull/271

**Comment by vchibikov** [comment]
Fix in https://github.com/Hydreon/Steadfast2/commit/8d8f101d3b8325475655d644d049c5f2f5f124a7
