### ISSUE TITLE
Server crashed when stopped it

### ISSUE THREAD

**Issue by SuperMaXAleX** [Hydreon/Steadfast2#269]
I simply wanted to stop my server, but it is crashed with that error : 
`[Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\command\CommandReader::unstack()" (EXCEPTION) in "/src/pocketmine/Thread" at line 79`

Using the latest Steadfast version & running on OS X El Capitan with PHP 7.0.2.
It was totally random.

**Comment by BI0MER** [comment]
What is your OS?

**Comment by SuperMaXAleX** [comment]
^

**Comment by BI0MER** [comment]
I have the same error on Windows every time, but on Debian (Ubuntu) everything is fine

**Comment by SuperMaXAleX** [comment]
Really strange error

**Comment by BI0MER** [comment]
and this #113 and this #222

**Comment by MrSmileCH** [comment]
solution:

public function quit(){
		$this->isKilled = true;
		$this->notify();
		if(!$this->isJoined()){
			if(!$this->isTerminated()){
				$this->join();
			}
		}
		ThreadManager::getInstance()->remove($this);
	}

**Comment by DavidBrockway** [comment]
This is not an issue, please update your mac to sierra OS.

**Comment by dktapps** [comment]
`unstack()` is not a `Thread` method, only `Worker`. Looks like code copy-paste.
