### ISSUE TITLE
The tables it can not fill there

### ISSUE THREAD

**Issue by hachkingtohach1** [Hydreon/Steadfast2#272]
The tables it can not fill there

**Comment by SuperMaXAleX** [comment]
1. We don’t what are you asking about
2. We don’t know what are you reporting
3. Use a correct English, please
4. Indicate everything you did to reproduce your issue

**Comment by BI0MER** [comment]
What a tables: enchanting tables, crafting tables?

**Comment by TheRoyalBlock** [comment]
This issue can be closed... It has been long enough
