### ISSUE TITLE
Anvils/Enchanting

### ISSUE THREAD

**Issue by junkdude** [Hydreon/Steadfast2#273]
Im not sure if they are even implemented but enchanting does not work on classic ui. Same goes for anvils. The changes are just client side.

**Comment by SuperMaXAleX** [comment]
It's not implemented.

**Comment by junkdude** [comment]
ah,

**Comment by vchibikov** [comment]
It should work. We will check this.

**Comment by junkdude** [comment]
nah they dont work for me

**Comment by vchibikov** [comment]
Enchanting fixed in https://github.com/Hydreon/Steadfast2/commit/87916cbc3dc1993f298819ec633c527a40e5d9b7
Anvil not implemented
