### ISSUE TITLE
I wanted to know why the following does not work:

### ISSUE THREAD

**Issue by MrSmileCH** [Hydreon/Steadfast2#275]
if($player->getItemInHand()->getId() == 388){
I mark this error:
 Error: "Call to a member function getItemInHand() on null"

**Comment by BI0MER** [comment]
getItemInHand -> search in this repositories -> function only in the class PlayerInventory -> сalled through inventory
Profit!

**Comment by xZeroMCPE** [comment]
Don't use ids. It's better to use the item directly like:

Item::EMERALD

**Comment by BI0MER** [comment]
@xZeroMCPE What's the difference, this is the choice of everyone

**Comment by xZeroMCPE** [comment]
Because the ID may change..... Don't rely on it.

**Comment by MrSmileCH** [comment]
I get the same error
if($pla->getItemInHand()->getId() == Item::EMERALD){
																			if($pla->hasPermission("sw.op")){
																				$this->fillChestsOP($levelArena);
																			}
																		}
[22:52:30] [Server thread/CRITICAL]: Could not execute task SkyWars\SkyWars\GameSender: Call to undefined method pocketmine\Player::getItemInHand()

con genisys no me pasa esto, lol

**Comment by xZeroMCPE** [comment]
Use this

``
$pla->getInventory()->getItemInHand()->getId() == Item::EMERALD){

}

the getItemInHand is on the player's inventory class, not the player class.
``
