### ISSUE TITLE
Slapper disappear on Server close

### ISSUE THREAD

**Issue by RompeCraneos** [Hydreon/Steadfast2#276]
SlappeHuman is disappearing on Server close...
Cause of Level.php Changes:

if (!$entity->isNeedSaveOnChunkUnload()) {
      $entity->close();
}

**Comment by BI0MER** [comment]
Look at this https://github.com/Hydreon/Steadfast2/commit/a8188b97e82990de717933bc36f93ce2eed21f2a and this https://github.com/Hydreon/Steadfast2/blob/master/src/pocketmine/entity/Human.php#L274

**Comment by RompeCraneos** [comment]
Thanks
