### ISSUE TITLE
Working with inventory

### ISSUE THREAD

**Issue by BI0MER** [Hydreon/Steadfast2#277]
I'm using setItem() function to fill the chests (there are no players in the world (chunks not loaded)), it returns TRUE, but the chest is empty. I get the inventory through $level->getTile(new Vector3($x, $y, $z))->getInventory(); and this tile instanceof Chest
And the chests in several chunks from the worldspawn are filled, but the rest of the world - no

**Comment by MrSmileCH** [comment]
Also to me it has happened the chunks have to load for the coffers to fill and that in a minigame is not well

**Comment by BI0MER** [comment]
@MrSmileCH But loadChunk() is present in the function:
https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/level/Level.php#L1971
https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/level/Level.php#L2207

**Comment by vchibikov** [comment]
@BI0MER Do you enabled auto-save in server.properties?
