### ISSUE TITLE
 What is this about what happens to me? I use the latest version

### ISSUE THREAD

**Issue by MrSmileCH** [Hydreon/Steadfast2#278]
![sin titulo](https://user-images.githubusercontent.com/27845246/28805593-dc2a3e08-7630-11e7-947e-1bc177be4f36.png)

**Comment by junkdude** [comment]
same thing for me

**Comment by xZeroMCPE** [comment]
SteadFast does not generate level..... Just load a region world into it.

**Comment by BI0MER** [comment]
@junkdude, @xZeroMCPE File `server.properties` set `auto-generate` value as `on`

**Comment by MrSmileCH** [comment]
Tomorrow I send a video because that happens to me and I do not find the reason

**Comment by SuperMaXAleX** [comment]
@junkdude File server.properties set auto-generate value as on
