### ISSUE TITLE
[1.2.0.2] Listing some issues

### ISSUE THREAD

**Issue by SuperMaXAleX** [Hydreon/Steadfast2#279]
**! I'LL UPDATE THIS POST EVERYTIMES I FOUND AN ISSUE !**

Here a list of issues with Minecraft 1.2's players with different players' versions : 

* If it's an anvil world, they see it totally corrupted.
* Sounds aren't working fine (because playing an other sound) or don't play anything.
* Items on Creative Inventory are totally disorganized, some variants of some blocks no longer appear [EVERY GUIs].
* Impossible to craft something and have, sometimes, this var_dump message : `string(17) "Recive bad recipe"` [EVERY GUIs]

_Searching more..._

**Comment by vchibikov** [comment]
1. We don't see problem with maps in Anvil format. It works well for us. May you provide your map.
2. _Minecraft 1.2's players can't change their skin in-game._ We don't implemented this yet, so it's not a bug))
3. Please provide more useful information about problems with transactions.

**Comment by SuperMaXAleX** [comment]
@vchibikov Okay

**Comment by xZeroMCPE** [comment]
@SuperMaXAleX Maybe it's corrupt or something.

**Comment by vchibikov** [comment]
- Nametag visible data flag isn't working since MC:PE 1.2.0.7
Client problem
 - If it's an anvil world, they see it totally corrupted.
Made some fixes.
 - Minecraft 1.2's players are invisible for others players, but we can still hit it.
Can not reproduce

**Comment by TheRoyalBlock** [comment]
The anvil world generated by the software ends up being totally blank and in the sky while using 1.2.0.9 (beta 3, came out earlier today)

**Comment by TheRoyalBlock** [comment]
Correction: All anvil worlds are totally corrupted in 1.2.0.9 unless copied from a PC server. I do not know why this is...

**Comment by TheRoyalBlock** [comment]
Full explanation:
I used my MCR worlds, it worked well, except some chunks were missing.
I converted MCR to Anvil, it appeared corrupted.
I used an anvil world that was generated automatically by steadfast during setup, it appeared corrupted.
I went to [this site](https://www.minecraftworldmap.com/worlds/7MHBW#/-146/64/64/-5/0/0) and downloaded the map, everything was flawless in terms of maps, The other stuff i don't know about, as I did not test.

**Comment by vchibikov** [comment]
@TheRoyalBlock Thanks, really thanks for informative bug message.
1 - 2. What converter do you use?
3. I switched generator to anvil and create new world in steadfast. And it works fine for me. May you show you server,properties and pocketmine.yml files content and also screenshot of corrupted anvil world.

**Comment by SuperMaXAleX** [comment]
"Minecraft 1.2's players are invisible for others players, but we can still hit it."'s bug has been fixed

**Comment by TheRoyalBlock** [comment]
@vchibikov I use [this](https://github.com/ImagicalCorp/MineConvert) and have been using it for many years. It has worked under many occasions, even on Tesseract for mcpe 1.0 conversions. 
In addition, after examining my pocketmine.yml file, it says,
```level-settings:
 #The default format that levels will use when created
 default-format: mcregion
 #If true, converts from a format that is not the default to the default format on load
 #NOTE: This is currently not implemented
 convert-format: false
```

**Comment by vchibikov** [comment]
@TheRoyalBlock All settings stores in `pocketmine.yml` and `server.properties`. By my opinion `server.properties` contains more useful settings then `pocketmine.yml`.

### About world stuff.
`server.properties` contains two option `auto-save` and `auto-generate`.
`auto-generate` - toggle for world generation (default: off)
`auto-save` - toggle for world auto-saving (default: off)

If `auto-generate` is disabled and you don't copied you map in worlds directory, then you will be spawned in empty world and be unable to move.

If `auto-save` is disabled all your changes will be lost after chunk unload (i.e. after it will come out off your render distance). What is more, map store not only block but also block entities like chest, sign, furnace and other. That means you will lost all sign text, chest contents and etc.

`default-format` from `pocketmine.yml` takes `mcregion` and `anvil` values.

### About commands
They should be added in `commands.json` in steadfast.

**Comment by TheRoyalBlock** [comment]
So I need auto-generate to be set to "on", I need pocketmine.yml to say "anvil". Okay. As per the commands, there should be an option for additional commands instead of manually adding to commands.json
