### ISSUE TITLE
[SUGGESTION] Add an event when we are interact with something on a customUI window

### ISSUE THREAD

**Issue by SuperMaXAleX** [Hydreon/Steadfast2#280]
Instead of making extends files of, for example, Button, create an event from the moment you interact with something in a customUI. It will be easier to manage and cleaner for everyone.

**Comment by vchibikov** [comment]
Modal windows doesn't work without implementation, so creating some sort of events in Steadfast is impossible.

**Comment by SuperMaXAleX** [comment]
Oh, okay. :/
And about implementation, what do I need to do when I’m extending, for example, the Button file ?
What I need to add on this file exactly ?

**Comment by SuperMaXAleX** [comment]
Okay, closing.
