### ISSUE TITLE
PlayerItemHeld Problem

### ISSUE THREAD

**Issue by RompeCraneos** [Hydreon/Steadfast2#282]
The PlayerItemHeldEvent isnt calling in slot change, only on player join the event is called

**Comment by daniktheboss** [comment]
1.2 has inventory changes

**Comment by vchibikov** [comment]
This event triggers when player changing item in hand. And it works fine for me on 1.2. I printing event instance in `setHeldItemSlot` method (this is the only one place where it uses) and id displayed correct data every time when i switching item. Also i checked it in plugin with same result. So checking your code first, maybe you forget write use for event.
