### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by GODLIKE5** [Hydreon/Steadfast2#283]
The tiles for old maps now appear as different blocks WTF 😂😱😭

**Comment by vchibikov** [comment]
You have three options.

First. Tell us what tiles you have problems with. And we will check it.

Or second. Make sure that you are not trying to use a map for PC version. Write a small code which displays block id when you interacting (hitting by hand) with it. Make sure that block id is matching with what you expecting. And then tell us what tiles you have problems with)

**Comment by BI0MER** [comment]
Or record it on video and show us

**Comment by GODLIKE5** [comment]
@vchibikov it's just like regular clay blocks
