### ISSUE TITLE
Phar (NOT A ISSUE)

### ISSUE THREAD

**Issue by Teamblocket** [Hydreon/Steadfast2#284]
Can i have a phar of this software? thanks

**Comment by GODLIKE5** [comment]
Why u can just use devtools and use /makeserver

**Comment by vchibikov** [comment]
We make changes quite often, so use DevTools plugin to create phar file by himself. You make get it by links bellow. Each link also contains small tutorial.

https://github.com/pmmp/PocketMine-DevTools
http://forums.pocketmine.net/plugins/devtools.515/
