### ISSUE TITLE
 Hi, I would like to know where in the Steadfast2 file this message appears that comes out to me in console

### ISSUE THREAD

**Issue by MrSmileCH** [Hydreon/Steadfast2#292]
moved wrongly!

**Comment by BI0MER** [comment]
There is no such message, please do a search on the repository.

**Comment by MrSmileCH** [comment]
It is like the antihack when moving too fast for stairs detects and leaves a message in console

**Comment by vchibikov** [comment]
May you give us example of message?

**Comment by MrSmileCH** [comment]
![sin titulo](https://user-images.githubusercontent.com/27845246/28907208-87896bcc-77e2-11e7-8fab-8b11ca68512f.png)

**Comment by MrSmileCH** [comment]
Only that appears to me in console

**Comment by MrSmileCH** [comment]
Found the error thanks: D
