### ISSUE TITLE
Incorrect working RCON

### ISSUE THREAD

**Issue by BI0MER** [Hydreon/Steadfast2#294]
I'm using https://github.com/thedudeguy/PHP-Minecraft-Rcon to connect with my SteadFast server. On the other core everything is in order (settings are the same), but here it gives an error. Because of this, I can not connect auto-donate service, it is the core bug?

Warning: unpack(): Type V: not enough input, need 4, have 0 in C:\Users\Vladislav\Desktop\SteadFast_Server\plugins\Lobby\src\BIOMER\Rcon.php on line 178
Warning: fread(): Length parameter must be greater than 0 in C:\Users\Vladislav\Desktop\SteadFast_Server\plugins\Lobby\src\BIOMER\Rcon.php on line 187
Warning: unpack(): Type V: not enough input, need 4, have 0 in C:\Users\Vladislav\Desktop\SteadFast_Server\plugins\Lobby\src\BIOMER\Rcon.php on line 188

**Comment by vchibikov** [comment]
Maybe or maybe not. RСON is not part of our immediate plans.

**Comment by BI0MER** [comment]
@vchibikov It is sad(
