### ISSUE TITLE
Bedrock can be destroyed by explosions

### ISSUE THREAD

**Issue by Guillaume351** [Hydreon/Steadfast2#300]
All is in the title.
Moreover, some blocks have problems like snow blocks that should drop snowballs but drop the raw block

**Comment by XDqrkneZ** [comment]
this can be done by a plugin

**Comment by SuperMaXAleX** [comment]
@XDqrkneZ Are you thinking this issue is normal ?

**Comment by SuperMaXAleX** [comment]
@XDqrkneZ Are you thinking this issue is normal ?

**Comment by XDqrkneZ** [comment]
@supermaXalex the "bedrock cN be destroyed by explosions" can be done by a plugin

**Comment by DavidBrockway** [comment]
This is not an issue, please close this fake issue.

**Comment by SuperMaXAleX** [comment]
@DavidBrockway This isn't one.

**Comment by SuperMaXAleX** [comment]
REPRODUCED.

@XDqrkneZ Are you dump or what ? 
Why are asking about "the "bedrock can be destroyed by explosions" can be done by a plugin" ?
This is an ISSUE. Not a plugin request.

**Comment by XDqrkneZ** [comment]
@supermaxalx what are you talking about lol? I only answered the title

**Comment by SuperMaXAleX** [comment]
Why are you answering the title of it’s not a question? Are you understanding it’s an ISSUE. Not a QUESTION.

**Comment by xZeroMCPE** [comment]
@SuperMaXAleX Shut the fuck up already, and CHILL. You're making such a big deal of something small.

**Comment by SuperMaXAleX** [comment]
@xZeroMCPE Sorry but in my dictionary, question !== issue.
I just explained, so don't come here to something useless as "Shut my month" lol

**Comment by DavidBrockway** [comment]
Close this

**Comment by DavidBrockway** [comment]
Bedrock can be destroyed by tnt just tested it

**Comment by Guillaume351** [comment]
@DavidBrockway That's the point. It should not be destroyed by TNT, but with Steadfast it does. So this is an issue

**Comment by DavidBrockway** [comment]
Yes I know I also don't like how the chunks are begging generated and TNT explosions lag the chunks that something that needs to be fixed as well.

**Comment by DavidBrockway** [comment]
Found the issue, working on fixing it.

**Comment by vchibikov** [comment]
Good luck. Closed
