### ISSUE TITLE
Do the SimpleForm crash my wrong usage or?

### ISSUE THREAD

**Issue by MuddyEGG** [Hydreon/Steadfast2#301]
CustomForm Can be fully working and return right data
but the Simpleform,I deleted the abstract and added the handle method
the server receive the player's click the button(return true
but...the client then crashes
I mean if I have done sth. wrong or it's a bug of the gui4-1.2MCPE
Furthermore,I wonder how I receive the the data of simpleform(which button the player clicks)

One more thing is that is there a way to change the text 'submit' on button(custom_form type)

**Comment by junkdude** [comment]
can u post how u got the data from the custom form?

**Comment by MuddyEGG** [comment]
@junkdude the handle function in /elements/customform/***
can get the data
I copied these files down into my plugin and make the handle return to my plugin

**Comment by MuddyEGG** [comment]
Pretty weird now...
Custom form using crashes too now(my app crashes)
I didn't touch my code even...

**Comment by MuddyEGG** [comment]
Got that
you can't send modal to players once they enter the server(but.um..why then)
after finishing the join event
They work right

**Comment by MuddyEGG** [comment]
Aha..added button id to post to the button
got the data from clicking the buttons
neat : )
