### ISSUE TITLE
[Question] How do we get the data from CustomForm

### ISSUE THREAD

**Issue by NidPlays** [Hydreon/Steadfast2#303]
I know how to send custom form but not how sure how to get the response to my plugin

**Comment by RedstoneAlmeida** [comment]
![image](https://user-images.githubusercontent.com/15146680/28978445-6ec86f44-791c-11e7-940d-8cf5203ae652.png)

**Comment by dishrex** [comment]
Each form window (https://github.com/Hydreon/Steadfast2/tree/master/src/pocketmine/customUI/windows) implements `CustomUI` and element (https://github.com/Hydreon/Steadfast2/tree/master/src/pocketmine/customUI/elements) extends `UIElement` they have `handle()` methods. When the server receives a `ModalFormResponsePacket` it sends the received data to the windows and  elements handle method. Which is where you want can put your logic to based on the data. 

So in your plugin just extend the windows and elements and use the handle.

**Comment by NidPlays** [comment]
Thanks!
