### ISSUE TITLE
All Plugins Commands not working

### ISSUE THREAD

**Issue by BlawoHD** [Hydreon/Steadfast2#307]

**Comment by DavidBrockway** [comment]
Could you please provide more information.

**Comment by TheRoyalBlock** [comment]
I'll try to reproduce this

**Comment by TheRoyalBlock** [comment]
Unable to reproduce.

**Comment by Asuna-Yuuki** [comment]
He means the commands are not working but you need to add those at json but that's not easy for some people so as i

**Comment by Asuna-Yuuki** [comment]
@TheRoyalBlock  @DavidBrockway  ^^

**Comment by vchibikov** [comment]
Ok. I will write the guide in couple of days.

**Comment by TheRoyalBlock** [comment]
For me, I didn't delete commands.json and yet it still takes it from plugin.yml :P
