### ISSUE TITLE
MOTD not Working

### ISSUE THREAD

**Issue by hachkingtohach1** [Hydreon/Steadfast2#308]
A error with MOTD it not working

**Comment by EpicArtz08999** [comment]
Go to src/pocketmine/network
Open file RakLibInterface.php
Change public $name = "Lifeboat Network"; to public $name = "Your server name";

**Comment by SuperMaXAleX** [comment]
Is it hard to do` $this->getServer()->getNetork()->setName(“The name of your server”);` ?

**Comment by vchibikov** [comment]
@hachkingtohach1 thanks for report.

**Comment by vchibikov** [comment]
fixed https://github.com/Hydreon/Steadfast2/commit/9db32fc1ca26e2d166fa06c2e38e0b1e73197ea6
