### ISSUE TITLE
Inventories before MC 1.2 are totally buggy

### ISSUE THREAD

**Issue by SuperMaXAleX** [Hydreon/Steadfast2#311]
The title says everything.
The hotbar doesn’t have correctly placed items, when doing clearAll(), it won’t update - you will need to tap the ground or interact with something else.
In Creative Mode, slots with air is ignored and returns to the old item we were holding.

It’s totally impossible to play with that old inventory. Hope you will fix this issue.

**Comment by vchibikov** [comment]
Fixed in https://github.com/Hydreon/Steadfast2/commit/61958f47e24e1efc77e5670c33ca16e47e8965b6 Check it please

**Comment by SuperMaXAleX** [comment]
I'll try it, thanks

**Comment by SuperMaXAleX** [comment]
@vchibikov It is almost fixed. It stills buggy in Creative mode.
