### ISSUE TITLE
Floating Particles Bug

### ISSUE THREAD

**Issue by GODLIKE5** [Hydreon/Steadfast2#313]
They are there but only from one angle you can see them :/?

**Comment by Guillaume351** [comment]
What MCPE version ? Can you show a screenshot/video ?

**Comment by GODLIKE5** [comment]
1.2.0.9 it's steadfast because Genisys Works fine

**Comment by SuperMaXAleX** [comment]
Genisys is no longer maintained.

**Comment by DarkYusuf13** [comment]
It maybe client problem

**Comment by TheRoyalBlock** [comment]
This was a client problem fixed in beta 4 (1.2.0.11). Try again

**Comment by GODLIKE5** [comment]
@SuperMaXAleX GenisysPro
