### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by RompeCraneos** [Hydreon/Steadfast2#318]
I update to latest steadfast version and this error occurs

PocketMine-Steadfast Crash Dump Fri Aug 11 22:02:28 UTC 2017

Error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 1953792 bytes)
File: /src/pocketmine/utils/Config
Line: 187
Type: E_ERROR

Code:
[178] 			switch($this->type){
[179] 				case Config::PROPERTIES:
[180] 				case Config::CNF:
[181] 					$content = $this->writeProperties();
[182] 					break;
[183] 				case Config::JSON:
[184] 					$content = json_encode($this->config, JSON_PRETTY_PRINT | JSON_BIGINT_AS_STRING);
[185] 					break;
[186] 				case Config::YAML:
[187] 					$content = yaml_emit($this->config, YAML_UTF8_ENCODING);
[188] 					break;
[189] 				case Config::SERIALIZED:
[190] 					$content = @serialize($this->config);
[191] 					break;
[192] 				case Config::ENUM:
[193] 					$content = implode("\r\n", array_keys($this->config));
[194] 					break;
[195] 			}
[196] 			@file_put_contents($this->file, $content, LOCK_EX);
[197] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.5.1 #0 [Protocol 101; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux e5-1620v3.1u-phx0.1.141.6.5.32.securedservers.com 2.6.32-573.12.1.el6.x86_64 #1 SMP Tue Dec 15 21:19:08 UTC 2015 x86_64
PHP Version: 7.0.20
Zend version: 3.0.0
OS : Linux, linux

**Comment by TheRoyalBlock** [comment]
Unable to repro

**Comment by GiantQuartz** [comment]
## Error: **Allowed memory size of 536870912 bytes exhausted**

**Comment by RompeCraneos** [comment]
You need a server with full people and plugins to reproduce Royal(100 players). And i never have this problem with previous build, processmovement problem occurs with server full too

**Comment by tigerza117** [comment]
Error: Allowed memory size of 536870912 bytes exhausted

**Comment by RompeCraneos** [comment]
memory leak on some new function

**Comment by junkdude** [comment]
this means u ran out of ram doesnt it?

**Comment by TheRoyalBlock** [comment]
It's a memory leak

**Comment by vchibikov** [comment]
Is it always link to  /src/pocketmine/utils/Config line 187?
And I think than 512MB RAM for 100 players it's small.
After that https://github.com/Hydreon/Steadfast2/commit/89ea295ddb10b236aa8a6e30f232662e84d4f685 we don't devide render distance, so currently more chunk loaded in same time. May be it reason of your error. Try change memory-limit in server.properties

**Comment by TheRoyalBlock** [comment]
Ah, @vchibikov. That's something that I forgot to discern. 512mb for 100 players is WAY too small

**Comment by GiantQuartz** [comment]
This is clearly a memory issue, I had this error too many times using small servers with too many plugins.

**Comment by TheRoyalBlock** [comment]
Yes. There used to be memory leaks all the time, but that was patched a while ago, now it's just too litttle memory given

**Comment by RompeCraneos** [comment]
I tried change memory at first crash.. but still giving me the same error :/

**Comment by RompeCraneos** [comment]
No more crash in last build now
