### ISSUE TITLE
Button::IMAGE_TYPE_PATH isn't working

### ISSUE THREAD

**Issue by SuperMaXAleX** [Hydreon/Steadfast2#321]
Doing `new Button("Simple test")->addImage(Button::IMAGE_TYPE_PATH, $this->getServer()->getDataPath() . "images/check-green-mark.png")` will give a corrupted [image](https://user-images.githubusercontent.com/19352571/29248948-48eb3c2e-8025-11e7-9934-12aa402bf962.png).

Here is the original [`check-green-mark.png`](https://user-images.githubusercontent.com/19352571/29248958-88d3e6a6-8025-11e7-88af-42924f994a1c.png).

**Comment by vchibikov** [comment]
Sorry but path not on your server but on client side. You should use it if you want use standard client items icons.
