### ISSUE TITLE
rcon does`nt work

### ISSUE THREAD

**Issue by kentikzlo** [Hydreon/Steadfast2#323]
I use rcon library by xPaw, on other cores it works. 

Warning: unpack(): Type V: not enough input, need 4, have 0 in /root/server/plugins/group/src/lib/Rcon.php on line 161

Warning: fread(): Length parameter must be greater than 0 in /root/server/plugins/group/src/lib/Rcon.php on line 168

Warning: unpack(): Type V: not enough input, need 4, have 0 in /root/server/plugins/group/src/lib/Rcon.php on line 169

**Comment by TheRoyalBlock** [comment]
Well, we are not those "other cores", we are Steadfast. Both the same and different. Some stuff will work, other will not.

**Comment by kentikzlo** [comment]
@TheRoyalBlock what i can do? i want that rcon work

**Comment by TheRoyalBlock** [comment]
at the moment, nothing. Simply be patient. I have used mcpe servers for many, many years without ever using rcon.

**Comment by vchibikov** [comment]
We already answered on the same question in https://github.com/Hydreon/Steadfast2/issues/294
