### ISSUE TITLE
NPC despawning

### ISSUE THREAD

**Issue by GiantQuartz** [Hydreon/Steadfast2#325]
I was testing my development's server when the NPC despawned in front of me.

![despawned](https://user-images.githubusercontent.com/21067195/29301314-8e2ebe58-817b-11e7-9047-3fe63214a323.png)

When I joined the game, the NPC was there again. (With my plugin, the NPC's are spawned again in PlayerJoinEvent)

![spawned](https://user-images.githubusercontent.com/21067195/29301307-83fef5d8-817b-11e7-9bda-84926460a210.png)

I cannot understand what is happening.

**Comment by vchibikov** [comment]
We don't have NPC class, so problem can be in our code. May you give more information.

**Comment by GiantQuartz** [comment]
My NPC class extends Human.
To spawn the NPC I do:
`BaseEntity::create("HumanStatue", $location);`

And I'm using EntityTeleportEvent and PlayerJoinEvent to spawn them. Is there any issue with that?

**Comment by hachkingtohach1** [comment]
You try to send a link to the steadfast version, which you are making your server go!

**Comment by GiantQuartz** [comment]
@hachkingtohach1 I always use the latest version.

**Comment by vchibikov** [comment]
Do you still have this problem?

**Comment by hachkingtohach1** [comment]
Ok I have problem with it
Vào 04-09-2017 11:28, "Victor Chibikov" <notifications@github.com> đã viết:

**Comment by DarkYusuf13** [comment]
Replace 

public function spawnTo(Player $player) {

to

public function spawnTo(Player $player) {
        if (!isset($this->hasSpawned[$player->getId()])) {
            $this->hasSpawned[$player->getId()] = $player;

**Comment by GiantQuartz** [comment]
@vchibikov Yes :')
@DarkYusuf13 I'm using Human's spawnTo method, and it already checks if the entity is spawned.

**Comment by TheRoyalBlock** [comment]
Perhaps we should **add** the npc class? It's quite an important feature...

**Comment by vchibikov** [comment]
@TheRoyalBlock Sounds like a plan

**Comment by hachkingtohach1** [comment]
I need company add NPC

**Comment by DarkYusuf13** [comment]
Try to look code of other npc plugins :) I hope you fix

**Comment by DarkYusuf13** [comment]
I think I found But can you send only spawnTo code?

**Comment by hachkingtohach1** [comment]
OK you can send for i a code spawn.
Vào 09-09-2017 00:11, "DarkYusuf13" <notifications@github.com> đã viết:

**Comment by DarkYusuf13** [comment]
Okay only send hasSpawned trust me I can fix. I was have this bug too but I fixed

**Comment by debil9877654321** [comment]
This is caused by auto-save.
