### ISSUE TITLE
Once again MOTD does not work with character id (I need the group you edit it)

### ISSUE THREAD

**Issue by hachkingtohach1** [Hydreon/Steadfast2#326]
When I run the MOTD server it works with the internal id, but however it does not work with the text id.

**Comment by vchibikov** [comment]
May you show some examples to illustrate what do you mean?

**Comment by hachkingtohach1** [comment]
My example is: ID No-IP or buy a DNS

**Comment by TheRoyalBlock** [comment]
That is not really an example... Please ive a more detailed example

**Comment by uselesswaifu** [comment]
May be wrong but he's saying the server does not ping when using a DNS Server
