### ISSUE TITLE
[1.2 only] Item consume not working

### ISSUE THREAD

**Issue by Guillaume351** [Hydreon/Steadfast2#328]
Eating, drinking potions... Don't work on 1.2

**Comment by vchibikov** [comment]
It works fine for me (1.2.0.22)  Please give a more detailed info.

**Comment by Guillaume351** [comment]
@vchibikov Eating is fixed in last beta, but potions are still broken, while they are working on 1.1 on the same server (when you drink it, it doesn't consume it, give you an empty bottle that disappear a few seconds later)

**Comment by vchibikov** [comment]
Ok, we'll check it out

**Comment by vchibikov** [comment]
Looks like it client bug. Client doesn't send use item event (EntityEventPacket)
