### ISSUE TITLE
Level-generator

### ISSUE THREAD

**Issue by ZloyNick** [Hydreon/Steadfast2#337]
When i rewrite generator (Normal.php, added some biomes, added BiomeSelector.php, etc.), chunks coudnt loading. No exceptions... And... WTF? Where debugging? xD

**Comment by tigerza117** [comment]
Steadfast2 not generator it work open minigame looooooooooooooool

**Comment by vchibikov** [comment]
Each programmer by itself should be a debugger)

**Comment by SuperMaXAleX** [comment]
@ZloyNick Have you set, on `server.properties`, `auto-generate` value on `on` ?
