### ISSUE TITLE
Inventory bug

### ISSUE THREAD

**Issue by RompeCraneos** [Hydreon/Steadfast2#350]
Cant put armor from my inventory or get items from chest, i tested in win10 and mcpe version 1.1.5

**Comment by vchibikov** [comment]
Armor works fine for me, chests also not cause troubles. Do you have this problems on vanilla Steadfast or you use some plugins?

**Comment by RompeCraneos** [comment]
using plugins, armor is good yes.. the problem is chest, no problems when im alone, but in my server with people this occurs a lot in skywars, sometimes no, but almost ever

**Comment by vchibikov** [comment]
Try reproduce it without plugins, with two devices. Or tell us how to reproduce it.

**Comment by akaSnapy** [comment]
@vchibikov I think he uses 1.1 versions, where the Classic aka PC gui is broken and fixed on 1.2

**Comment by TheRoyalBlock** [comment]
oh

**Comment by RompeCraneos** [comment]
Yes, some solution or fix?

**Comment by TheRoyalBlock** [comment]
All softwares have had numerous problems with the pre-1.2 windows 10 edition ui. I have not personally found a solution, nor have my other coding friends, but I believe someone else certainly has...

**Comment by GiantQuartz** [comment]
@TheRoyalBlock All UI bugs were client-sided, they were fixed in the latest Minecraft 1.2 build.

**Comment by TheRoyalBlock** [comment]
yes, that's what I just pointed out. Minecraft 1.2 fixed it, but when connecting with older clients the UI is messed up. that's what the problem is

**Comment by TheRoyalBlock** [comment]
As @vchibikov pointed out in another issue, pre-1.2 support will be cut in a few days/weeks. Therefore, there is no point in fixing old inventories if the work will be irrelevant soon.

*Close this*
