### ISSUE TITLE
Undefined offset

### ISSUE THREAD

**Issue by GiantQuartz** [Hydreon/Steadfast2#352]
`Notice: Undefined offset: 0 in C:\Users\MediaService\Desktop\development\PM\Servers\Steadfast server\src\pocketmine\level\format\generic\BaseFullChunk.php on line 212`
This happens to me all time, even if I haven't any plugin enabled.

**Comment by DarkYusuf13** [comment]
Update steadfast if still not fixed I think caused by your world

**Comment by vchibikov** [comment]
Does it happen on concrete map or all maps? Did you made any changes in Steadfast?

**Comment by vchibikov** [comment]
Could you check. I think https://github.com/Hydreon/Steadfast2/commit/b9fde26f3629d1b45eb7c1cf4cf4bf896c3699bd may be fix it

**Comment by GiantQuartz** [comment]
Fixed, thanks.
