### ISSUE TITLE
MC Client Crash

### ISSUE THREAD

**Issue by kaitododoyt** [Hydreon/Steadfast2#354]
Crash on Fly and other sometimes, i dont know the reason: Anvil Map format , without plugins

https://www.youtube.com/watch?v=xnqIeHRilBQ&feature=youtu.be

**Comment by kaitododoyt** [comment]
after https://github.com/Hydreon/Steadfast2/commit/6dc111150925451a83d65653dd6dfdc55539d37d

**Comment by MrSmileCH** [comment]
hey kaito I want to buy the skywares plugin compatible with steadfast where can I contact you?

**Comment by TheRoyalBlock** [comment]
somewhere else, the comment can be deleted for spam

**Comment by vchibikov** [comment]
Platform, client version.

**Comment by vchibikov** [comment]
On еру other hand, in your video you receive the socket error (socket_recvfrom(): unable to recvfrom [10054]). I don't know spanish(?), so i 'googled' the error and found description.

> An existing connection was forcibly closed by the remote host.

As it error happens on server, so remote host is your client. Maybe you send some bad data. Try disable all plugins (or one by one) and reproduce it again.

**Comment by kaitododoyt** [comment]
Ok i'll test tomorrow, but is strange.. i reverted the commit "small fix in data for FullChunkDatPacket" and this dont occurs more..

**Comment by kaitododoyt** [comment]
Still occuring in vanilla server: Anvil Map only, with w10 edition and MCPE clients

**Comment by vchibikov** [comment]
fixed https://github.com/Hydreon/Steadfast2/commit/b9fde26f3629d1b45eb7c1cf4cf4bf896c3699bd
