### ISSUE TITLE
16 chunks, and the walls appear, how to remove them?

### ISSUE THREAD

**Issue by flayzer** [Hydreon/Steadfast2#361]
![666](https://user-images.githubusercontent.com/28701906/30201868-f1424fe8-9484-11e7-8b5c-732a0433fd9e.png)

16 chunks, and the walls appear, how to remove them, and then the load reaches 20%

**Comment by GiantQuartz** [comment]
Edit your `server.properties` file, theorically, switching `auto-generate` to off should be enough.
