### ISSUE TITLE
generateLevel does not generate levels

### ISSUE THREAD

**Issue by Kevin-Reinke** [Hydreon/Steadfast2#362]
Function generateLevel in Server.php is bugged and does not generate levels, even the default one.

**Comment by Kevin-Reinke** [comment]
Fixed by using the old function, whoever committed the new version of the function is... Don't commit untested code!

**Comment by Kevin-Reinke** [comment]
Reopened so that issue can be addressed!

**Comment by vchibikov** [comment]
What means "old function"? Last time this function was changed 2 months ago.

**Comment by Kevin-Reinke** [comment]
The old version of it.

**Comment by vchibikov** [comment]
Are you set auto-generate in true in server.properties file?
