### ISSUE TITLE
Fully Commands.json

### ISSUE THREAD

**Issue by DenzelCode** [Hydreon/Steadfast2#364]
Where are the fully commands.json? -_- why you changed the commands logic, the default are perfect

**Comment by DenzelCode** [comment]
Please put a options on pocketmine.yml to disable or able the commands.json, i hate it

**Comment by vchibikov** [comment]
If you doesn't create json file in your plugin all commands will be taken from yml file.

**Comment by TheRoyalBlock** [comment]
he's talking about the steadfast commands.json. many people dislike how their command usage is restricted. however, if I remember correctly, you made some changes so now all commands can be used. am I right?
