### ISSUE TITLE
Color Armor

### ISSUE THREAD

**Issue by sc00scoc** [Hydreon/Steadfast2#365]
$tempTag = new Compound("", []);
$tempTag->customColor = new IntTag("customColor", 0x00ffff00);
$helmet->setCompound($tempTag);

Error: segmentation fault
I think the problem is this 0x00ffff00 but in other Core is Work!

**Comment by Sandertv** [comment]
The problem is that you wrote `new Compound("", []);` when  it should be `new CompoundTag("", []);`

**Comment by vchibikov** [comment]
Your code works for me. Let's start with standard questions) Do you have any plugins or just vanilla steadfast? What is your PC operation system? Where you get PHP?

**Comment by sc00scoc** [comment]
1- I have a single plugin that I created if I try to run that part of the code the server stops. I've already tested everything by debugging and I can be sure that the problem is that part of code...
2- centos-7-x86_64 
3- https://bintray.com/pocketmine/PocketMine/ 

All function 
    public function setPlayerTeam($team, Player $player) {
        if ($team == "red") {
            $player->setNameTag(C::RED . $player->getName());
            $helmet = Item::get(298);
            $chestplate = Item::get(299);
            $tempTag = new Compound("", []);
            $tempTag->customColor = new IntTag("customColor", 0x00ff1a1a);
            $helmet->setCompound($tempTag);
            $chestplate->setCompound($chestplate);
            $player->getInventory()->setChestplate($chestplate);
            $player->getInventory()->setHelmet($helmet);
      }
}

**Comment by sc00scoc** [comment]
And $player->getInventory()->clearAll() is not work for armor!

**Comment by vchibikov** [comment]
You have a typo in `$chestplate->setCompound($chestplate);` i think should be `$chestplate->setCompound($tempTag);`. This is the reason of segmentation fault.

**Comment by sc00scoc** [comment]
I had not even noticed ... would the bug be for clearAll?
I also found another bug... The armor seems not to be displayed on win10 
![screenshot_10](https://user-images.githubusercontent.com/25847440/30275862-251c94b0-9703-11e7-9fe5-4121f028d676.jpg)
![photo5886704750701947382](https://user-images.githubusercontent.com/25847440/30275876-31e34ff4-9703-11e7-8632-e1e6ecb51474.jpg)

**Comment by vchibikov** [comment]
For now all armor changes sends only for viewers of player but not for the player himself. You should use `sendArmorContents` to send all changes to player.
