### ISSUE TITLE
This is what the version needs to upgrade.[Company Hyplex™®]

### ISSUE THREAD

**Issue by hachkingtohach1** [Hydreon/Steadfast2#366]
I work at a server programming company and I think the PocketMine-steadfast version needs to improve the generator to make the minegames run when it does not lead to sleeping minegames for the server.

**Comment by TheRoyalBlock** [comment]
1st: There is no need to specify your "expertise" in the topic, it will not improve or disprove your point.
2nd: While this is a reasonable suggestion, it has many errors such as lack of description in your request, improper english, and strange terms making it hard to read and understand.
