### ISSUE TITLE
bug number online player?

### ISSUE THREAD

**Issue by MrSmileCH** [Hydreon/Steadfast2#368]
![sin titulo1](https://user-images.githubusercontent.com/27845246/30301113-466dbd86-971e-11e7-869f-0f556039845a.png)

![sin titulo](https://user-images.githubusercontent.com/27845246/30301043-bf27170a-971d-11e7-9da0-fc8ce164edc7.png)
does not display the number of online players

**Comment by vchibikov** [comment]
Couldn't reproduce. Do you use QueryRegenerateEvent in your plugins? What client version do you use?

**Comment by MrSmileCH** [comment]
no friend, I have done it without plugins and it happens to me the same, I use the most recent versions that you get every 24 hours

**Comment by TheRoyalBlock** [comment]
I cannot reproduce either. This is not the software's fault. Either: bad client, or bad plugin. 

*Close this*
