### ISSUE TITLE
MOTD Bug?

### ISSUE THREAD

**Issue by ItzBulkDev** [Hydreon/Steadfast2#37]
The MOTD is unchangeable for some reason it say Lifeboat Network

**Comment by xxFlare** [comment]
You can change it in RakLibInterface.

**Comment by ItzBulkDev** [comment]
@xxFlare What is the file path for that?

**Comment by ItzBulkDev** [comment]
@xxFlare nvm

**Comment by xxFlare** [comment]
https://github.com/Hydreon/Steadfast2/blob/master/src/pocketmine/network/RakLibInterface.php#L65
