### ISSUE TITLE
Posible crash server

### ISSUE THREAD

**Issue by MrSmileCH** [Hydreon/Steadfast2#371]
PocketMine-Steadfast Crash Dump Wed Sep 13 13:47:43 EDT 2017

Error: Call to a member function getSpawn() on null
File: /src/pocketmine/level/Level
Line: 2324
Type: notice

Code:
[2315] 	/**
[2316] 	 * Returns true if the spawn is part of the spawn
[2317] 	 *
[2318] 	 * @param int $X
[2319] 	 * @param int $Z
[2320] 	 *
[2321] 	 * @return bool
[2322] 	 */
[2323] 	public function isSpawnChunk($X, $Z){
[2324] 		$spawnX = $this->provider->getSpawn()->getX() >> 4;
[2325] 		$spawnZ = $this->provider->getSpawn()->getZ() >> 4;
[2326] 
[2327] 		return abs($X - $spawnX) <= 1 and abs($Z - $spawnZ) <= 1;
[2328] 	}
[2329] 
[2330] 	/**
[2331] 	 * Returns the raw spawnpoint
[2332] 	 *
[2333] 	 * @deprecated
[2334] 	 * @return Position

Backtrace:
#0 /src/pocketmine/level/Level(529): pocketmine\level\Level->unloadChunkRequest(integer 4, integer 1, boolean 1)
#1 /src/pocketmine/Player(2676): pocketmine\level\Level->freeChunk(integer 4, integer 1, pocketmine\Player Player(2085))
#2 /src/pocketmine/network/RakLibInterface(142): pocketmine\Player->close(string , string client disconnect)
#3 /src/raklib/server/ServerHandler(137): pocketmine\network\RakLibInterface->closeSession(string 186.144.20.102:35886, string client disconnect)
#4 /src/pocketmine/network/RakLibInterface(122): raklib\server\ServerHandler->handlePacket(boolean)
#5 /src/pocketmine/network/Network(178): pocketmine\network\RakLibInterface->process(boolean)
#6 /src/pocketmine/Server(2488): pocketmine\network\Network->processInterfaces(boolean)
#7 /src/pocketmine/Server(2267): pocketmine\Server->tick(boolean)
#8 /src/pocketmine/Server(2141): pocketmine\Server->tickProcessor(boolean)
#9 /src/pocketmine/Server(1736): pocketmine\Server->start(boolean)
#10 /src/pocketmine/PocketMine(459): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string /home/minecraft-pe-2/server/, string /home/minecraft-pe-2/server/, string /home/minecraft-pe-2/server/plugins/)

PocketMine-MP version: 1.5.1 #0 [Protocol 101; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux ns502617.ip-192-95-30.net 2.6.32-openvz-amd64 #1 SMP Thu Mar 6 16:34:46 MSK 2014 x86_64
PHP Version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
SimpleAuth 1.7.2 by PocketMine Team, shoghicp for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
FaceLogin 1.0.0 by Muqsit for API(s) 1, 12, 0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
BuycraftPM 0.4 by Tebex Limited for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
CommandBlocker 1.5.5 by Thunder33345 for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
AntiSpamPro 1.3.1 by awzaw for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
SClearLagg 1 by Sergey_Dertan for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
KitsSkyWars 1.1.1-alpha by MrSmile for API(s) 1.0.0, 1.1.0, 1.14.0, 2.0.0, 2.1.0, 3.0.0-ALPHA1, 3.0.0, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8
GlobalBan 1.0 by LazzKiller for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
Slapper 1.3.5 by jojoe77777 for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
SW_svile 0.7dev by svile for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
RealTime 2.1.1 by Guillaume351 for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
RestartMe 1.2.0 by Gamecrafter for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
RealMute 3.4.1 by Leo3418 for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
Denuncia 1.0 by ImCrack for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
Elytra-Fly 1 by takesi for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
1vs1 0.0.4 by  for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
ClearChat 1.0.0 by  for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
DevTools 1.12.0 by PocketMine Team for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
PerWorldChat 1.3 by EvolSoft for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
ManyWorlds 2.0.3 by aliuly for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
NoAdvertisingPE 1.0.1 by Vaivez66 for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
WorldProtect 2.2.0 by aliuly for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
MagicServer 1.0.1 by kvetinac97 for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
AntiVoid 1.0.0 by KairusDarkSeeker for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
CheckID 1.0-Alpha by XxD7omGamer for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15, 3.0.0-ALPHA16, 3.0.0-ALPHA17, 3.0.0-ALPHA18, 3.0.0-ALPHA19, 3.0.0-ALPHA20
Really_simple_warp 2.0.0 by Yomogiβ for API(s) 1.12.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2 3

**Comment by TheRoyalBlock** [comment]
Please give instructions to reproduce.
Also, make sure you are using the latest version
Also, try to reproduce it without the plugins.

**Comment by MrSmileCH** [comment]
this has happened with the latest version, and it continues to happen, with plugins and without plugins

**Comment by TheRoyalBlock** [comment]
steps to reproduce?

**Comment by MrSmileCH** [comment]
the server is on for a few hours and suddenly the server stops and crash happens

**Comment by vchibikov** [comment]
Do you use multi levels? Looks like you(or one of plugin) incorrectly call Server::unloadLevel when player log out.

**Comment by MrSmileCH** [comment]
I use several worlds, it happens to me very often, about every 24 hours
