### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by sc00scoc** [Hydreon/Steadfast2#377]
1 - $player->setTitle("title", "subtitle", 3000) not work, Title is static!
2 - $player->removeItem($item) now work in Win10

**Comment by GiantQuartz** [comment]
1. 3.000 seconds are 50 minutes, have you been 50 minutes online to check if the title disappeared? I don't think so.
2. I tried to reproduce the issue, but removeItem() works fine for me. Are you using the latest Steadfast version?

**Comment by kentikzlo** [comment]
@GiantQuartz 1. 3000 ticks is 150 sec (-_-) and it`s 2.5mins

**Comment by GiantQuartz** [comment]
@kentikzlo setTitle() uses seconds, not ticks.

**Comment by sc00scoc** [comment]
ok ty

**Comment by TheRoyalBlock** [comment]
*Close this*
