### ISSUE TITLE
Question regarding simple form UI

### ISSUE THREAD

**Issue by briananderson99** [Hydreon/Steadfast2#378]
Hi,

So I've setup some simple form UI's with buttons, the only issues I'm having is images, I want to use the client sided images so I used "path" someone told me you could use item images in-client thru that instead of thru an internet url, I tried "apple.png", "apple", "4" and a few others and can't seem to get it to work. Does anyone know which directory it reads out of in the client? assets folder?

**Comment by vchibikov** [comment]
For apple `textures/items/apple`
I would advise you to download the apk and unzip it. All images stores in `assets/resource_packs/vanilla/textures`
