### ISSUE TITLE
How to make minegames not steep ?

### ISSUE THREAD

**Issue by hachkingtohach1** [Hydreon/Steadfast2#379]
When I start server 9 hours , server will steep minegames

**Comment by vchibikov** [comment]
@hachkingtohach1 What are minegames? How it related to steadfast? What do you want?

**Comment by hachkingtohach1** [comment]
When I run the SurvivalGames plugin, I've created many arena. After 9 hours, the server will warn config.php at line case Config :: YAML:
$ content = self :: fixYAMLIndexes ($ content);
$ this-> config = yaml_parse ($ content); . Then the arena I registered was sleeping.

**Comment by hachkingtohach1** [comment]
When I run the SurvivalGames plugin, I've created many arena. After 9
hours, the server will warn config.php at line case Config :: YAML:
$ content = self :: fixYAMLIndexes ($ content);
$ this-> config = yaml_parse ($ content); . Then the arena I registered was
sleeping.

Vào 19 thg 9, 2017 12:05, "Victor Chibikov" <notifications@github.com> đã
viết:

**Comment by GiantQuartz** [comment]
@vchibikov He is probably speaking about a plugin.
@hachkingtohach1 If you are having issues with your plugin it is probably your own fault, maybe by syntax errors or the most extended ones: **logical errors**.  Otherwise it could be a Steadfast2 memory leak, but I don't think so.

**Comment by TheRoyalBlock** [comment]
*Close this*
