### ISSUE TITLE
Issue with adding item to hotbar

### ISSUE THREAD

**Issue by ItzBulkDev** [Hydreon/Steadfast2#38]
Upon tapping an item in the creative inventory, it will not appear in the hotbar

**Comment by xxFlare** [comment]
Oh, this is an MCPE bug correlating with a broken packet, shoghicp made a hack-fix for this on PM but it will lag the server upon chest opening.

Use PM if you want creative mode.

**Comment by ItzBulkDev** [comment]
ah. so creative will work once the MCPE developers fixes this bug?
