### ISSUE TITLE
1.2?

### ISSUE THREAD

**Issue by XDqrkneZ** [Hydreon/Steadfast2#381]
Does it support 1.2? Sorry for the bother

**Comment by GiantQuartz** [comment]
It has been supporting it since the first build

**Comment by vchibikov** [comment]
@XDqrkneZ steadfast supports 1.2 from version 1.2.0.20 to latest. Other 1.2 versions also may connect to server, but respawn doesn't work for them. We are going completely remove support for protocol less then 134 (1.2.0.20) within a week or two.

**Comment by TheRoyalBlock** [comment]
*Close this*
