### ISSUE TITLE
Api?

### ISSUE THREAD

**Issue by LolNova** [Hydreon/Steadfast2#391]
What api does steadfast2 uses

**Comment by WiliRodin** [comment]
1.12.0

**Comment by LolNova** [comment]
so it's doesn't use like Api 2.0.0 or 3.0.0

**Comment by WiliRodin** [comment]
Ye.
Steadfast doesn't use that apis.

**Comment by TheShermanTanker** [comment]
Its the latest server version dont worry but the API version iz still labelled as 1.12.0
