### ISSUE TITLE
CubedHost - How to get phar

### ISSUE THREAD

**Issue by SirDoz** [Hydreon/Steadfast2#392]
im having issues making the server phar because im using multicraft.

can someone give me a phar version of steadfast? thanks

**Comment by EpicArtz08999** [comment]
Dont use steadfast if you dont even know how to develop, I will ruin your server.

**Comment by WiliRodin** [comment]
Ye it will destroy your server.

**Comment by SirDoz** [comment]
i dont have anything on it. so if it did destroy the server it wont be a much of a deal

**Comment by WiliRodin** [comment]
Try build the code in Travis CI or Appveyor or CircleCi
