### ISSUE TITLE
What behind packet??

### ISSUE THREAD

**Issue by flayzer** [Hydreon/Steadfast2#397]
![tfn6riir5ce](https://user-images.githubusercontent.com/32015623/30805719-501b0464-a1fb-11e7-9fe6-f73dd9be96bb.jpg)

**Comment by GiantQuartz** [comment]
I don't quite understand your question, but if you are looking for the corresponding packets to open and work with forms you can use [ModalFormResponsePacket](https://github.com/Hydreon/Steadfast2/blob/master/src/pocketmine/network/protocol/v120/ModalFormResponsePacket.php) and [ShowModalFormPacket](https://github.com/Hydreon/Steadfast2/blob/master/src/pocketmine/network/protocol/v120/ShowModalFormPacket.php), anyway, you can use the CustomUI provided [here](https://github.com/Hydreon/Steadfast2/tree/master/src/pocketmine/customUI).
