### ISSUE TITLE
Not So much an issue, But I'm having a tough time configuring

### ISSUE THREAD

**Issue by matatacmca** [Hydreon/Steadfast2#399]
Hi There,

I'm having a tough time configuring the server.

I have been able to install successfully on Ubuntu 16, but I am having difficulty setting the server to run automatically on start up.

could you perhaps include a section in the readme.md that will show how to configure this?

Regards

**Comment by flayzer** [comment]
This can be configured in the start.sh | DO_LOOP=off

**Comment by matatacmca** [comment]
Thanks

Not sure if this works. But I managed to configure it as a service.

Perhaps you should include a guide for that?
