### ISSUE TITLE
Inventory bugs 1.2

### ISSUE THREAD

**Issue by ZloyNick** [Hydreon/Steadfast2#404]
Fix crafting and anything actions with inventory.

You can see bugs here: play.detreex.ru:19132

/r <your pass> - register

When you will registered, try to send /wild command, cut tree and try crafting items and blocks. This instruction only for users, who doesnt knows russian.

**Comment by ZloyNick** [comment]
Sorry for my bad english, im russian :/

**Comment by TheShermanTanker** [comment]
Sorry, can you try to rephrase?

**Comment by vchibikov** [comment]
https://github.com/Hydreon/Steadfast2/commit/5903a46b9ed8fea42fb353760b611b832ce92159
