### ISSUE TITLE
MEET THE GENISYS PRO !

### ISSUE THREAD

**Issue by betty294** [Hydreon/Steadfast2#408]
OUR ADVANCE TEAM ARE SOME FROM NASA . SOME EVEN HELP WIL PHP 7!

SUPERXOINGKING - CREATOR OF GENISYS PRO!

APPLEDEVELOPS - MASTER DEVELOP HELPED US WITH TYPEHINT

DERTDERRDY - TRUSTED MEMBER GIVES ME GOOD ADVICE

MASTEROFTHEREALM - MAIN WORKER ON GENISYSPRO

CORTEXT PE - FUCKS EVERYTHING UP

- FRAGO - FROM NASA, EVEN HELPS WITH PHP7 ! GOOD DEV!

TOGETHER WE WILL MAKE THE BEST GENISYS TO BEAT POCKETMEIN! WE NOT SELL FOR PROFDITS

**Comment by MasterOfTheRealm** [comment]
Can you damn shut up and not include me in your unstable mental behavior?
because of you people are starting to hate me.
So just get a life and disappear or you'll be messing with the wrong people soon "Betty".

**Comment by betty294** [comment]
@masteroftherealm its importannt genispro team give credits for work pu it

even superxoingking say you did good hard work job ! you should be pround of your genisyspro heritage

i want to give credit and special thank to all

**Comment by MasterOfTheRealm** [comment]
So why spam all the software repos? Is this your idea on entertainment? Do you not have better things to do? If you want to do something good then just shut up and disappear. That's the best thing you can do for all of us. Just be quiet and disappear. You can't keep hiding forever. And when people find out who you really are... you are in for a world of pain. So be smart and stop now.

**Comment by betty294** [comment]
@MasterOfTheRealm i will tell gurun you try to ruin genisys pro after interaction limit off !

**Comment by MasterOfTheRealm** [comment]
You asked for it is all i can say "Betty". Good Luck surviving... Not.
