### ISSUE TITLE
MASTEROFTHEREALMS IS TRYING TO DISCOURAGE ME AND GURUN FROM GENISYS PRO PROJECT !

### ISSUE THREAD

**Issue by betty294** [Hydreon/Steadfast2#409]
I WILL AKE SURE TO SPREAD THIS TO EVERY SPOON/FORK

**Comment by GiantQuartz** [comment]
Please stop spamming Hydreon issue tracker, your project isn't getting popular, it is getting a very bad fame thanks to your spam.
@vchibikov Can you close this and all his issues, please?

**Comment by SuperMaXAleX** [comment]
Ban him
