### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by Creeperface01** [Hydreon/Steadfast2#42]
Fatal error: Uncaught exception 'ArrayOutOfBoundsException' with message 'Undefined offset: 2' in C:\Users\Honza\Documents\PocketMine-MP\src\pocketmine\Server.php on line 1424

ArrayOutOfBoundsException: Undefined offset: 2 in C:\Users\Honza\Documents\PocketMine-MP\src\pocketmine\Server.php on line 1424

Call Stack:
    0.0069     127032   1. {main}() C:\Users\Honza\Documents\PocketMine-MP\src\pocketmine\PocketMine.php:0
    0.4150     264112   2. pocketmine\Server->__construct() C:\Users\Honza\Documents\PocketMine-MP\src\pocketmine\PocketMine.php:465
    0.5391     366696   3. ExceptionHandler::handler() C:\Users\Honza\Documents\PocketMine-MP\src\pocketmine\PocketMine.php:1424

**Comment by tntloverlol** [comment]
Please Pastebin the Crashdump and paste the link here
