### ISSUE TITLE
Call to undefined method pocketmine\Player::getAttributeMap()

### ISSUE THREAD

**Issue by flayzer** [Hydreon/Steadfast2#436]
[Остановка сервера/CRITICAL]: Error: "Call to undefined method pocketmine\Player::getAttributeMap()" (EXCEPTION) in "/plugins/core/src/Setting/Data/Solo/arena" at line 412

line 412: if ($player->getAttributeMap() != null) {

**Comment by vchibikov** [comment]
Your plugin not suitable with steadfast
