### ISSUE TITLE
Bug In 1.1 and 1.2

### ISSUE THREAD

**Issue by Amirgta1** [Hydreon/Steadfast2#440]
Hello
1-In 1.2, you can skip but do not display Command
2-In 1.1, Command Plugins can not be used
3-The purechat plugin does not work properly
[http://s8.picofile.com/file/8310658618/photo_%DB%B2%DB%B0%DB%B1%DB%B7_%DB%B1%DB%B1_%DB%B0%DB%B1_%DB%B1%DB%B7_%DB%B4%DB%B2_%DB%B1%DB%B5.jpg](url)

**Comment by wyt3dr4g0n** [comment]
I'm starting to wonder if their devs even care anymore

**Comment by Amirgta1** [comment]
😭

**Comment by Amirgta1** [comment]
With Api 1.12.0 we came together
No slappers and EssentialsPE plugins
We do not have Cid
We came along with Command.json
We do not have the Resource Pack

I did not ask for a lot. Just said, solve problems 1.2 and 1.1

**Comment by Amirgta1** [comment]
I solved all the bug Haro for myself
I just wanted to say you did nothing
Bye
