### ISSUE TITLE
How to fix that when you hit it a hand the player loses 1.5 hp

### ISSUE THREAD

**Issue by flayzer** [Hydreon/Steadfast2#441]
How to fix that when you hit it a hand the player loses 1.5 hp??

**Comment by XDqrkneZ** [comment]
so when you hit a player with your fist, they lose 1.5 hp?

**Comment by xZeroMCPE** [comment]
@flayzer 
You can fix it with a simple plugin.

Just modify the damage or better, add health to the player.
