### ISSUE TITLE
Dropped item movement is buggy

### ISSUE THREAD

**Issue by debil9877654321** [Hydreon/Steadfast2#448]
When I drop item from my inventory it's lagged in air for 0.5 seconds
Please fix it.

**Comment by debil9877654321** [comment]
Maybe bad entity ticking?

**Comment by ZloyNick** [comment]
May be.

**Comment by debil9877654321** [comment]
Where's function which tick entities located? Can't find it.

**Comment by ZloyNick** [comment]
You can found it at Level.php

**Comment by debil9877654321** [comment]
What function exactly?
