### ISSUE TITLE
Why i cant change max height to 255?

### ISSUE THREAD

**Issue by ZloyNick** [Hydreon/Steadfast2#451]
I have changed max y value to 255 in McRegion, but mountains doents generates highter than 128... (elevation etc. changed too)

**Comment by ZloyNick** [comment]
![screenshot_20171123-193305](https://user-images.githubusercontent.com/23015694/33229174-5a73f63a-d1eb-11e7-9477-ffb8cfeaeb1c.png)
![screenshot_20171123-220204](https://user-images.githubusercontent.com/23015694/33229150-de88a58e-d1ea-11e7-9ef0-f644f0acc5fa.png)
![screenshot_20171123-185816](https://user-images.githubusercontent.com/23015694/33229153-f6fe1efa-d1ea-11e7-909b-b1dd6bae707f.png)
![screenshot_20171122-214333](https://user-images.githubusercontent.com/23015694/33229157-0bf2cce8-d1eb-11e7-8391-0f810723f2ae.png)

**Comment by ZloyNick** [comment]
I noticed that at the height of 129 to put a thigh, and above - the ungenerated blocks

**Comment by ZloyNick** [comment]
Sorry for my english, I'm Russian ...

**Comment by dktapps** [comment]
The McRegion world format is ancient. It doesn't support worlds of any different height than 128. Use Anvil.

**Comment by ZloyNick** [comment]
Ok, thanks!
