### ISSUE TITLE
Can't connect to the world

### ISSUE THREAD

**Issue by MrKeliser** [Hydreon/Steadfast2#516]
Hello. When trying to connect to the server, an error occurs: "Can not connect to the world". Game version 1.2.11

**Comment by Yexeed** [comment]
че лох не работает ничего да. Ну плагинописание же фигня, те кто пишут плагины их даже кодерами не назвать

**Comment by Yexeed** [comment]
когда держал сервер 7 месяцев но не можешь адекватно поставить ядро

**Comment by MrKeliser** [comment]
Yexeed, ага

**Comment by zyware** [comment]
@MrKeliser op, ты собрался для выживания использовать? если да напиши vk.com/zyware обьясню кое что, сервер умрет сразу.

**Comment by MrKeliser** [comment]
@zyware, нет. Хотел использовать для лобби.

**Comment by DevLedock** [comment]
## ха лох ебаный

**Comment by An0ther1337** [comment]
Угар

**Comment by MrKeliser** [comment]
@DevLedock, не вижу причин для агрессии. Это показывает как минимум твою некомпетентность.

**Comment by endervlad** [comment]
Хах, стедик кака:3

**Comment by corndan** [comment]
@MrKeliser верни 20к Илье и 200 рублей Вадиму

**Comment by magickitten** [comment]
чё тут?

**Comment by MrKeliser** [comment]
@corndan, очень интересно. За что, я должен Вадиму возвращать 200 рублей? Работу сделанную, он сразу удалил.

**Comment by Yexeed** [comment]
@MrKeliser за то что вадим сделал эту работу
