### ISSUE TITLE
How to use SteadFast?

### ISSUE THREAD

**Issue by EnderKenji** [Hydreon/Steadfast2#53]
Can teach me how to install steadfast? Thanks.

**Comment by GamerXzavier** [comment]
you using android or pc or ios?

**Comment by GamerXzavier** [comment]
if fir android or ios you make the page to destop version on the below the github page and there a for zip download

**Comment by EnderKenji** [comment]
I downloaded,, and then?

**Comment by GamerXzavier** [comment]
put the file at plugin and use devtools and make /makeplugin (name)

**Comment by EnderKenji** [comment]
Ok ,, I will try.

**Comment by EnderKenji** [comment]
Is the hunger fixed? I did the wht u said, but i think its doesnt work,, the hunger still not fix... maybe failed

**Comment by GamerXzavier** [comment]
yeah maybe someone else make a new hungergames plugin

**Comment by EnderKenji** [comment]
Then ok... ._.
