### ISSUE TITLE
MCPE-Market.com

### ISSUE THREAD

**Issue by RandomAltThingy** [Hydreon/Steadfast2#61]
Hey guys,

I was wondering if it would be alright for you guys (Or me if you want) to compile every major build of Steadfast2 and submit it to http://mcpe-market.com? This would make it easier for server owners to setup using this software, and less spam of people asking how to compile it!

To submit to website, sign up > click resources > click submit resource > choose PocketMine Phars category.
 To update the resource there will be a button on the resources' page.

Thanks and if you need any more info DM TheDiamondYT (Me) on the website.

**Comment by PEMapModder** [comment]
@RandomAltThingy nothing is simpler than automation.

![[xkcd 1319](//xkcd.com/1319)](https://imgs.xkcd.com/comics/automation.png)

**Comment by RandomAltThingy** [comment]
@PEMapModder What are you saying?

**Comment by RandomAltThingy** [comment]
That i should compile it automatically?

**Comment by RandomAltThingy** [comment]
I made this issue to ask them for permission and see if they would like to create an account and submit it themselves, or would want me to (If I got the permission)

**Comment by PEMapModder** [comment]
I am suggesting that it is more efficient that you create a service that automatically pushes releases onto it via the XenForo API.

**Comment by KnownUnown** [comment]
This is kind of an open source project...we don't require permission for distributing builds. Just don't sell builds and you'll be fine.

**Comment by RandomAltThingy** [comment]
Alright thanks for the info
