### ISSUE TITLE
API 2.0.0?

### ISSUE THREAD

**Issue by TonyWAV** [Hydreon/Steadfast2#78]
Hey canou update this to api 2.0.0

**Comment by MhikeiMPC** [comment]
You might want to consider moving on to Genisys... This fork is dead..

**Comment by DavidJBrockway** [comment]
Hi the fork is not dead i am currently working on it regards to the api 2.0.0 that for pocketmine steadyfast 2 is for lbsg and thgeir plugin not pocketmine

**Comment by thebigsmileXD** [comment]
Its not dead. There is PHP7, and everyday new pull requests.

**Comment by MhikeiMPC** [comment]
hi on the readme it says for pocketmine 0.13.0 we are on 0.14.3 so pdate it

**Comment by MhikeiMPC** [comment]
And you still might want to go to Genisys because no chat saving and your inv wont save so its not good if you want to run a server

**Comment by xxFlare** [comment]
@TonyWAV Is their a specific API you need that is not here? I don't think PocketMines API changed much due to in activeness.

**Comment by jrodr10** [comment]
Now.... now its dead
