### ISSUE TITLE
Fix for Gliching into ground

### ISSUE THREAD

**Issue by thebigsmileXD** [Hydreon/Steadfast2#80]
https://github.com/Hydreon/Steadfast2/blob/master/src/pocketmine/entity/Entity.php#L773
Change Y to Z https://github.com/ClearSkyTeam/ClearSky/commit/df29aa0ad38f9cf2afa4924a81975426edd8fff5

**Comment by tntloverlol** [comment]
That branch is no longer being maintained use the php7 branch instead.

**Comment by thebigsmileXD** [comment]
Doesnt the php7 branch have the same glich anyways?
