### ISSUE TITLE
Block Break no sound and small partical

### ISSUE THREAD

**Issue by DavidJBrockway** [Hydreon/Steadfast2#95]
Hi i am a dev i found a fix for the break block no partial shows or it shows small and block break makes no noice i have the fix via mediafire so the owner of lbsg plz send me an email for the code to repair this bug at email is Zena196970@gmail.com

**Comment by thebigsmileXD** [comment]
https://github.com/ClearSkyTeam/ClearSky/blob/master/src/pocketmine/level/Level.php#L1684
vs.
https://github.com/Hydreon/Steadfast2/blob/master/src/pocketmine/level/Level.php#L1273

**Comment by DavidJBrockway** [comment]
What

**Comment by thebigsmileXD** [comment]
This is how you can fix the bug.

**Comment by DavidJBrockway** [comment]
I don't know I looked in the code is also found it it was true also I am working on adding doors my first exempt failed idk why

**Comment by thebigsmileXD** [comment]
Doors should be easy, just do new classes that extend door. Feel free to check @ClearSkyTeam 's code :P

**Comment by DavidJBrockway** [comment]
read my email and my new pull

**Comment by DavidJBrockway** [comment]
can i help clearsky
 out

**Comment by vchibikov** [comment]
not interested
